// ============================================================================
// SKILLS DICTIONARY — used by AI resume scoring
// ============================================================================

export const TECH_SKILLS = [
  "javascript",
  "typescript",
  "react",
  "react native",
  "angular",
  "vue",
  "svelte",
  "next.js",
  "nuxt",
  "node.js",
  "express",
  "nestjs",
  "python",
  "django",
  "flask",
  "fastapi",
  "java",
  "spring",
  "spring boot",
  "kotlin",
  "go",
  "golang",
  "rust",
  "c",
  "c++",
  "c#",
  ".net",
  "ruby",
  "rails",
  "php",
  "laravel",
  "swift",
  "objective-c",
  "dart",
  "flutter",
  "sql",
  "mysql",
  "postgresql",
  "mongodb",
  "redis",
  "elasticsearch",
  "dynamodb",
  "cassandra",
  "graphql",
  "rest",
  "grpc",
  "aws",
  "azure",
  "gcp",
  "google cloud",
  "docker",
  "kubernetes",
  "terraform",
  "ansible",
  "jenkins",
  "github actions",
  "gitlab ci",
  "ci/cd",
  "linux",
  "nginx",
  "apache",
  "git",
  "html",
  "css",
  "sass",
  "tailwind",
  "bootstrap",
  "webpack",
  "vite",
  "babel",
  "jest",
  "mocha",
  "cypress",
  "playwright",
  "selenium",
  "machine learning",
  "deep learning",
  "tensorflow",
  "pytorch",
  "pandas",
  "numpy",
  "scikit-learn",
  "data science",
  "data engineering",
  "spark",
  "hadoop",
  "kafka",
  "rabbitmq",
  "microservices",
  "serverless",
  "blockchain",
  "solidity",
  "figma",
  "sketch",
  "adobe xd",
] as const;

export const SOFT_SKILLS = [
  "leadership",
  "communication",
  "teamwork",
  "problem-solving",
  "critical thinking",
  "adaptability",
  "time management",
  "project management",
  "agile",
  "scrum",
  "mentoring",
  "collaboration",
  "presentation",
  "negotiation",
  "conflict resolution",
  "creativity",
  "attention to detail",
  "organization",
  "decision making",
  "strategic thinking",
  "customer service",
  "analytical skills",
  "research",
  "writing",
  "public speaking",
] as const;

export const ALL_SKILLS = [...TECH_SKILLS, ...SOFT_SKILLS] as const;

export type TechSkill = (typeof TECH_SKILLS)[number];
export type SoftSkill = (typeof SOFT_SKILLS)[number];
