CREATE TABLE IF NOT EXISTS countries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(3) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  currency VARCHAR(3) NOT NULL,
  currency_symbol VARCHAR(5) NOT NULL DEFAULT '',
  region VARCHAR(20) NOT NULL DEFAULT 'asia',
  min_wage_monthly BIGINT NULL,
  payroll_frequency VARCHAR(20) NOT NULL DEFAULT 'monthly',
  tax_year_start VARCHAR(5) NOT NULL DEFAULT '01-01',
  has_social_security BOOLEAN DEFAULT TRUE,
  has_pension BOOLEAN DEFAULT TRUE,
  has_health_insurance BOOLEAN DEFAULT TRUE,
  notice_period_days INT DEFAULT 30,
  probation_months INT DEFAULT 3,
  max_work_hours_week INT DEFAULT 40,
  annual_leave_days INT DEFAULT 20,
  public_holidays INT DEFAULT 10,
  is_active BOOLEAN DEFAULT TRUE,
  compliance_notes TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS global_employees (
  id INT AUTO_INCREMENT PRIMARY KEY,
  organization_id INT UNSIGNED NOT NULL,
  empcloud_user_id INT UNSIGNED NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(128) NOT NULL,
  country_id INT NOT NULL,
  employment_type VARCHAR(20) NOT NULL DEFAULT 'eor',
  contract_type VARCHAR(20) NOT NULL DEFAULT 'full_time',
  job_title VARCHAR(200),
  department VARCHAR(100) NULL,
  start_date DATE NOT NULL,
  end_date DATE NULL,
  salary_amount BIGINT NOT NULL DEFAULT 0,
  salary_currency VARCHAR(3) NOT NULL DEFAULT 'USD',
  salary_frequency VARCHAR(20) NOT NULL DEFAULT 'monthly',
  status VARCHAR(20) NOT NULL DEFAULT 'onboarding',
  tax_id VARCHAR(50) NULL,
  bank_name VARCHAR(100) NULL,
  bank_account VARCHAR(50) NULL,
  bank_routing VARCHAR(50) NULL,
  contract_document_url VARCHAR(500) NULL,
  notes TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_org_status (organization_id, status),
  INDEX idx_org_country (organization_id, country_id)
);

CREATE TABLE IF NOT EXISTS global_payroll_runs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  organization_id INT UNSIGNED NOT NULL,
  country_id INT NOT NULL,
  period_month INT NOT NULL,
  period_year INT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'draft',
  total_gross BIGINT DEFAULT 0,
  total_deductions BIGINT DEFAULT 0,
  total_employer_cost BIGINT DEFAULT 0,
  total_net BIGINT DEFAULT 0,
  currency VARCHAR(3) NOT NULL DEFAULT 'USD',
  exchange_rate_to_base DECIMAL(15,6) DEFAULT 1,
  approved_by INT UNSIGNED NULL,
  paid_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_org_period (organization_id, period_year, period_month)
);

CREATE TABLE IF NOT EXISTS global_payroll_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  payroll_run_id INT NOT NULL,
  organization_id INT UNSIGNED NOT NULL,
  global_employee_id INT NOT NULL,
  gross_salary BIGINT NOT NULL DEFAULT 0,
  tax_amount BIGINT DEFAULT 0,
  social_security_employee BIGINT DEFAULT 0,
  social_security_employer BIGINT DEFAULT 0,
  pension_employee BIGINT DEFAULT 0,
  pension_employer BIGINT DEFAULT 0,
  health_insurance_employee BIGINT DEFAULT 0,
  health_insurance_employer BIGINT DEFAULT 0,
  other_deductions BIGINT DEFAULT 0,
  net_salary BIGINT NOT NULL DEFAULT 0,
  total_employer_cost BIGINT NOT NULL DEFAULT 0,
  currency VARCHAR(3) NOT NULL DEFAULT 'USD',
  notes TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contractor_invoices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  organization_id INT UNSIGNED NOT NULL,
  global_employee_id INT NOT NULL,
  invoice_number VARCHAR(50) NOT NULL,
  amount BIGINT NOT NULL DEFAULT 0,
  currency VARCHAR(3) NOT NULL DEFAULT 'USD',
  description TEXT NULL,
  period_start DATE,
  period_end DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  submitted_at DATETIME,
  approved_by INT UNSIGNED NULL,
  paid_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS compliance_checklist (
  id INT AUTO_INCREMENT PRIMARY KEY,
  organization_id INT UNSIGNED NOT NULL,
  global_employee_id INT NOT NULL,
  item VARCHAR(255) NOT NULL,
  is_completed BOOLEAN DEFAULT FALSE,
  completed_at DATETIME NULL,
  completed_by INT UNSIGNED NULL,
  due_date DATE NULL,
  category VARCHAR(20) NOT NULL DEFAULT 'legal',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT IGNORE INTO countries (code, name, currency, currency_symbol, region, annual_leave_days, public_holidays, notice_period_days, probation_months, max_work_hours_week) VALUES
('IN','India','INR','Rs','asia',24,14,30,6,48),
('US','United States','USD','$','americas',0,11,14,3,40),
('GB','United Kingdom','GBP','GBP','europe',28,8,30,3,48),
('DE','Germany','EUR','EUR','europe',20,10,30,6,40),
('FR','France','EUR','EUR','europe',25,11,30,4,35),
('CA','Canada','CAD','C$','americas',10,10,14,3,40),
('AU','Australia','AUD','A$','oceania',20,8,14,6,38),
('SG','Singapore','SGD','S$','asia',7,11,30,6,44),
('AE','United Arab Emirates','AED','AED','middle_east',30,14,30,6,48),
('JP','Japan','JPY','JPY','asia',10,16,30,3,40),
('BR','Brazil','BRL','R$','americas',30,12,30,3,44),
('MX','Mexico','MXN','$','americas',12,7,15,1,48),
('KR','South Korea','KRW','KRW','asia',15,15,30,3,40),
('NL','Netherlands','EUR','EUR','europe',20,8,30,2,40),
('ES','Spain','EUR','EUR','europe',22,14,15,6,40),
('IT','Italy','EUR','EUR','europe',20,12,30,6,40),
('SE','Sweden','SEK','kr','europe',25,13,30,6,40),
('CH','Switzerland','CHF','Fr','europe',20,8,30,3,45),
('IE','Ireland','EUR','EUR','europe',20,10,30,6,48),
('PL','Poland','PLN','zl','europe',20,13,30,3,40),
('PH','Philippines','PHP','PHP','asia',5,18,30,6,48),
('ID','Indonesia','IDR','Rp','asia',12,15,30,3,40),
('MY','Malaysia','MYR','RM','asia',8,11,30,3,48),
('TH','Thailand','THB','THB','asia',6,16,30,4,48),
('VN','Vietnam','VND','VND','asia',12,11,30,2,48),
('ZA','South Africa','ZAR','R','africa',15,12,30,3,45),
('NG','Nigeria','NGN','NGN','africa',6,11,30,3,40),
('KE','Kenya','KES','KSh','africa',21,10,30,3,52),
('EG','Egypt','EGP','EGP','middle_east',21,8,30,3,48),
('SA','Saudi Arabia','SAR','SAR','middle_east',21,9,90,3,48);
