// ============================================================================
// COUNTRY PAYROLL CONFIGS — data for the config-driven engine
// (packages/server/src/services/tax/country-payroll.service.ts)
//
// Each entry is a complete real ruleset for one country: annual income-tax
// bands, mandatory contribution funds (PF/ESIC equivalents) with employee /
// employer rates and monthly caps, and payroll levies. Figures are 2025/26,
// independently researched + fact-checked (all HIGH confidence). See
// ProjectDocumentation/payroll-statutory-top20-countries.md.
//
// Countries with bespoke logic keep dedicated services and are NOT here:
//   IN (india-tax), US (us-tax), GB (uk-tax), ZA (za-tax).
// ============================================================================

import type { CountryPayrollConfig } from "./country-payroll.service";

export const COUNTRY_CONFIGS: Record<string, CountryPayrollConfig> = {
  // China — confidence: high. Shanghai rates for the 2025 contribution year, effective 1 Jul 2025 – 30 Jun 2026 (announced by the Shanghai HRSS Bureau on 18 Sep 2025, based on the 2024 Shanghai average monthly wage of CNY 12,434). Social-insurance contribution base ceiling = 300% (CNY 37,302/mo), floor = 60% …
  CN: {
    code: "CN",
    name: "China",
    currency: "CNY",
    subunitDivisor: 100,
    taxYear: "2025 (calendar year)",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 36000, rate: 3 },
        { min: 36000, max: 144000, rate: 10 },
        { min: 144000, max: 300000, rate: 20 },
        { min: 300000, max: 420000, rate: 25 },
        { min: 420000, max: 660000, rate: 30 },
        { min: 660000, max: 960000, rate: 35 },
        { min: 960000, max: Infinity, rate: 45 },
      ],
      annualAllowance: 60000,
      annualRebate: 0,
    },
    funds: [
      {
        name: "Basic Pension Insurance (\u517b\u8001\u4fdd\u9669)",
        purpose: "pension",
        employeeRate: 8,
        employerRate: 16,
        monthlyCap: 37302,
        monthlyFloor: 7460,
      },
      {
        name: "Basic Medical Insurance incl. Maternity (\u533b\u7597+\u751f\u80b2\u4fdd\u9669)",
        purpose: "health",
        employeeRate: 2,
        employerRate: 9,
        monthlyCap: 37302,
        monthlyFloor: 7460,
      },
      {
        name: "Unemployment Insurance (\u5931\u4e1a\u4fdd\u9669)",
        purpose: "unemployment",
        employeeRate: 0.5,
        employerRate: 0.5,
        monthlyCap: 37302,
        monthlyFloor: 7460,
      },
      {
        name: "Work-Related Injury Insurance (\u5de5\u4f24\u4fdd\u9669)",
        purpose: "disability",
        employeeRate: 0,
        employerRate: 0.2,
        monthlyCap: 37302,
        monthlyFloor: 7460,
      },
      {
        name: "Housing Provident Fund (\u4f4f\u623f\u516c\u79ef\u91d1)",
        purpose: "housing",
        employeeRate: 7,
        employerRate: 7,
        monthlyCap: 37302,
        monthlyFloor: 7460,
      },
    ],
    notes:
      "Shanghai rates for the 2025 contribution year, effective 1 Jul 2025 \u2013 30 Jun 2026 (announced by the Shanghai HRSS Bureau on 18 Sep 2025, based on the 2024 Shanghai average monthly wage of CNY 12,434). Social-insurance contribution base ceiling = 300% (CNY 37,302/mo), floor = 60% (CNY 7,460/mo). Medical and maternity insurance are merged; the 9% employer medical rate reflects the stage-reduced schedule effective 1 Mar 2025\u201328 Feb 2026 (8.5% basic incl. maternity + 0.5% local supplementary medical); employee medical rate is 2%. Work-injury rate is industry-risk-dependent (benchmark 0.2%\u20131.9%); t",
  },
  // Japan — confidence: high. Tokyo assumed. Health & long-term-care rates are the Kyokai Kenpo (協会けんぽ) Tokyo Branch FY2025 rates effective March 2025 (health 9.91% total, care 1.59% nationwide total, each split 50/50 employee/employer); health rates vary by prefecture. Employment insurance uses the general-b…
  JP: {
    code: "JP",
    name: "Japan",
    currency: "JPY",
    subunitDivisor: 1,
    taxYear: "2025 (calendar year)",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 1950000, rate: 5 },
        { min: 1950000, max: 3300000, rate: 10 },
        { min: 3300000, max: 6950000, rate: 20 },
        { min: 6950000, max: 9000000, rate: 23 },
        { min: 9000000, max: 18000000, rate: 33 },
        { min: 18000000, max: 40000000, rate: 40 },
        { min: 40000000, max: Infinity, rate: 45 },
      ],
      annualAllowance: 580000,
      annualRebate: 0,
    },
    funds: [
      {
        name: "Employees' Pension Insurance (\u539a\u751f\u5e74\u91d1\u4fdd\u967a)",
        purpose: "pension",
        employeeRate: 9.15,
        employerRate: 9.15,
        monthlyCap: 650000,
        monthlyFloor: 88000,
      },
      {
        name: "Health Insurance (\u5065\u5eb7\u4fdd\u967a \u2013 Kyokai Kenpo Tokyo)",
        purpose: "health",
        employeeRate: 4.955,
        employerRate: 4.955,
        monthlyCap: 1390000,
        monthlyFloor: 58000,
      },
      {
        name: "Long-term Care Insurance (\u4ecb\u8b77\u4fdd\u967a, ages 40\u201364)",
        purpose: "health",
        employeeRate: 0.795,
        employerRate: 0.795,
        monthlyCap: 1390000,
        monthlyFloor: 58000,
      },
      {
        name: "Employment Insurance (\u96c7\u7528\u4fdd\u967a, general business)",
        purpose: "unemployment",
        employeeRate: 0.55,
        employerRate: 0.9,
      },
      {
        name: "Workers' Accident Compensation Insurance (\u52b4\u707d\u4fdd\u967a, general/office)",
        purpose: "disability",
        employeeRate: 0,
        employerRate: 0.3,
      },
      {
        name: "Child-rearing Contribution (\u5b50\u3069\u3082\u30fb\u5b50\u80b2\u3066\u62e0\u51fa\u91d1)",
        purpose: "general",
        employeeRate: 0,
        employerRate: 0.36,
        monthlyCap: 650000,
        monthlyFloor: 88000,
      },
    ],
    levies: [
      {
        name: "Special Reconstruction Surtax (\u5fa9\u8208\u7279\u5225\u6240\u5f97\u7a0e)",
        rate: 2.1,
        paidBy: "employee",
        base: "income_tax",
      },
      {
        name: "Local Inhabitant Tax (\u4f4f\u6c11\u7a0e, Tokyo \u2013 flat rate portion)",
        rate: 10,
        paidBy: "employee",
        base: "gross",
      },
    ],
    notes:
      "Tokyo assumed. Health & long-term-care rates are the Kyokai Kenpo (\u5354\u4f1a\u3051\u3093\u307d) Tokyo Branch FY2025 rates effective March 2025 (health 9.91% total, care 1.59% nationwide total, each split 50/50 employee/employer); health rates vary by prefecture. Employment insurance uses the general-business FY2025 rate effective April 2025 (employee 0.55% / employer 0.9%, total 1.45%; agriculture/forestry/fishery/sake/construction differ). Long-term care applies only to insured persons aged 40\u201364. Workers' accident insurance is employer-only and industry-dependent (~0.3% for office/general '\u305d\u306e\u4ed6\u306e\u5404\u7a2e\u4e8b\u696d'; up to 8.8% f",
  },
  // Germany — confidence: high. National statutory rates for 2025. Income-tax bands approximate the geometrically progressive tariff (Sec. 32a EStG) using the official 2025 corner values (12,096 / 17,443 / 68,430 / 277,825) with representative marginal rates; the 14%-24% sub-band split is an approximation of th…
  DE: {
    code: "DE",
    name: "Germany",
    currency: "EUR",
    subunitDivisor: 100,
    taxYear: "2025 (calendar year)",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 12096, rate: 0 },
        { min: 12096, max: 17443, rate: 14 },
        { min: 17443, max: 68430, rate: 24 },
        { min: 68430, max: 277825, rate: 42 },
        { min: 277825, max: Infinity, rate: 45 },
      ],
      annualAllowance: 1230,
      annualRebate: 0,
    },
    funds: [
      {
        name: "Pension insurance (Rentenversicherung)",
        purpose: "pension",
        employeeRate: 9.3,
        employerRate: 9.3,
        monthlyCap: 8050,
      },
      {
        name: "Unemployment insurance (Arbeitslosenversicherung)",
        purpose: "unemployment",
        employeeRate: 1.3,
        employerRate: 1.3,
        monthlyCap: 8050,
      },
      {
        name: "Health insurance (Krankenversicherung, incl. 2.5% avg supplementary rate)",
        purpose: "health",
        employeeRate: 8.55,
        employerRate: 8.55,
        monthlyCap: 5512.5,
      },
      {
        name: "Long-term care insurance (Pflegeversicherung, parent base rate; excl. Saxony split and childless surcharge)",
        purpose: "disability",
        employeeRate: 1.8,
        employerRate: 1.8,
        monthlyCap: 5512.5,
      },
    ],
    levies: [
      {
        name: "Solidarity surcharge (Solidaritaetszuschlag)",
        rate: 5.5,
        paidBy: "employee",
        base: "income_tax",
      },
      {
        name: "Insolvency contribution (Insolvenzgeldumlage)",
        rate: 0.15,
        paidBy: "employer",
        base: "gross",
      },
    ],
    notes:
      "National statutory rates for 2025. Income-tax bands approximate the geometrically progressive tariff (Sec. 32a EStG) using the official 2025 corner values (12,096 / 17,443 / 68,430 / 277,825) with representative marginal rates; the 14%-24% sub-band split is an approximation of the smooth 14->42% progression. Church tax (Kirchensteuer, 8-9% of income tax) is excluded. Health insurance uses the 14.6% general rate plus the 2.5% average supplementary rate (split equally since 2019). Long-term care shown at the standard parent rate split 1.8%/1.8%; excludes the Saxony-specific split (employee 2.3% ",
  },
  // France — confidence: high. France has no sub-national (regional/communal) personal income tax; national rates apply everywhere. Income-tax bands are the officially adopted 2025 barème on 2024 income (loi de finances n°2025-127 du 14 février 2025, art. 2; 1.8% indexation). They are per-part (the barème is a…
  FR: {
    code: "FR",
    name: "France",
    currency: "EUR",
    subunitDivisor: 100,
    taxYear: "2025 (calendar year)",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 11497, rate: 0 },
        { min: 11497, max: 29315, rate: 11 },
        { min: 29315, max: 83823, rate: 30 },
        { min: 83823, max: 180294, rate: 41 },
        { min: 180294, max: Infinity, rate: 45 },
      ],
      annualAllowance: 0,
      annualRebate: 0,
    },
    funds: [
      {
        name: "Assurance maladie-maternit\u00e9 (health/sickness)",
        purpose: "health",
        employeeRate: 0,
        employerRate: 7,
      },
      {
        name: "Assurance vieillesse plafonn\u00e9e (basic state pension, capped)",
        purpose: "pension",
        employeeRate: 6.9,
        employerRate: 8.55,
        monthlyCap: 3925,
      },
      {
        name: "Assurance vieillesse d\u00e9plafonn\u00e9e (basic state pension, uncapped)",
        purpose: "pension",
        employeeRate: 0.4,
        employerRate: 2.02,
      },
      {
        name: "Retraite compl\u00e9mentaire Agirc-Arrco Tranche 1",
        purpose: "pension",
        employeeRate: 3.15,
        employerRate: 4.72,
        monthlyCap: 3925,
      },
      {
        name: "Retraite compl\u00e9mentaire Agirc-Arrco Tranche 2",
        purpose: "pension",
        employeeRate: 8.64,
        employerRate: 12.95,
        monthlyCap: 31400,
        monthlyFloor: 3925,
      },
      {
        name: "Contribution d'\u00e9quilibre g\u00e9n\u00e9ral (CEG) Tranche 1",
        purpose: "pension",
        employeeRate: 0.86,
        employerRate: 1.29,
        monthlyCap: 3925,
      },
      {
        name: "Contribution d'\u00e9quilibre g\u00e9n\u00e9ral (CEG) Tranche 2",
        purpose: "pension",
        employeeRate: 1.08,
        employerRate: 1.62,
        monthlyCap: 31400,
        monthlyFloor: 3925,
      },
      {
        name: "Contribution d'\u00e9quilibre technique (CET, salaries above 1 PMSS)",
        purpose: "pension",
        employeeRate: 0.14,
        employerRate: 0.21,
        monthlyCap: 31400,
      },
      {
        name: "Assurance ch\u00f4mage (unemployment)",
        purpose: "unemployment",
        employeeRate: 0,
        employerRate: 4,
        monthlyCap: 15700,
      },
      {
        name: "AGS (wage guarantee fund)",
        purpose: "unemployment",
        employeeRate: 0,
        employerRate: 0.25,
        monthlyCap: 15700,
      },
      {
        name: "Allocations familiales (family benefits)",
        purpose: "general",
        employeeRate: 0,
        employerRate: 3.45,
      },
      {
        name: "Contribution solidarit\u00e9 autonomie (CSA, disability/autonomy)",
        purpose: "disability",
        employeeRate: 0,
        employerRate: 0.3,
      },
      {
        name: "FNAL (housing fund, employers <50 staff)",
        purpose: "housing",
        employeeRate: 0,
        employerRate: 0.1,
        monthlyCap: 3925,
      },
      {
        name: "APEC (executive/cadre employment association)",
        purpose: "unemployment",
        employeeRate: 0.024,
        employerRate: 0.036,
        monthlyCap: 15700,
      },
      {
        name: "Contribution \u00e0 la formation professionnelle (vocational training, \u226511 staff)",
        purpose: "training",
        employeeRate: 0,
        employerRate: 1,
      },
    ],
    levies: [
      {
        name: "CSG (Contribution sociale g\u00e9n\u00e9ralis\u00e9e, on 98.25% of gross)",
        rate: 9.2,
        paidBy: "employee",
        base: "gross",
      },
      {
        name: "CRDS (Contribution au remboursement de la dette sociale, on 98.25% of gross)",
        rate: 0.5,
        paidBy: "employee",
        base: "gross",
      },
      {
        name: "Taxe d'apprentissage (apprenticeship tax)",
        rate: 0.68,
        paidBy: "employer",
        base: "gross",
      },
      { name: "Contribution au dialogue social", rate: 0.016, paidBy: "employer", base: "gross" },
    ],
    notes:
      "France has no sub-national (regional/communal) personal income tax; national rates apply everywhere. Income-tax bands are the officially adopted 2025 bar\u00e8me on 2024 income (loi de finances n\u00b02025-127 du 14 f\u00e9vrier 2025, art. 2; 1.8% indexation). They are per-part (the bar\u00e8me is applied after the quotient familial divides net taxable income by the household's number of parts). NOTE: the later 2026 bar\u00e8me (revenus 2025) uses higher thresholds (11,600 / 29,579 / 84,577 / 181,917) \u2014 this config is intentionally kept internally consistent to 2025 (PMSS \u20ac3,925). A 10% standard deduction for professi",
  },
  // Italy — confidence: high. National (state-level) figures only. Regional IRPEF surcharge (addizionale regionale, ~1.23%-3.33%) and municipal IRPEF surcharge (addizionale comunale, ~0%-0.9%) are EXCLUDED as they vary by region/comune. incomeTax.annualRebate=1955 is the base employee employment tax credit (d…
  IT: {
    code: "IT",
    name: "Italy",
    currency: "EUR",
    subunitDivisor: 100,
    taxYear: "2025 (calendar year)",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 28000, rate: 23 },
        { min: 28000, max: 50000, rate: 35 },
        { min: 50000, max: Infinity, rate: 43 },
      ],
      annualAllowance: 0,
      annualRebate: 1955,
    },
    funds: [
      {
        name: "INPS Pension IVS (Fondo Pensioni Lavoratori Dipendenti)",
        purpose: "pension",
        employeeRate: 9.19,
        employerRate: 23.81,
        monthlyCap: 10050.58,
      },
      {
        name: "INPS Additional 1% Pension Contribution (aliquota aggiuntiva L.438/1992)",
        purpose: "pension",
        employeeRate: 1,
        employerRate: 0,
        monthlyCap: 10050.58,
        monthlyFloor: 4620.67,
      },
      {
        name: "Unemployment Insurance (NASpI / assicurazione contro la disoccupazione)",
        purpose: "unemployment",
        employeeRate: 0,
        employerRate: 1.61,
      },
    ],
    notes:
      "National (state-level) figures only. Regional IRPEF surcharge (addizionale regionale, ~1.23%-3.33%) and municipal IRPEF surcharge (addizionale comunale, ~0%-0.9%) are EXCLUDED as they vary by region/comune. incomeTax.annualRebate=1955 is the base employee employment tax credit (detrazione da lavoro dipendente, 2025 value, raised from 1,880) which is flat for income up to EUR 15,000 but then changes/phases out at higher income, reaching EUR 0 at EUR 50,000; a trattamento integrativo top-up applies for low earners - net effect creates a no-tax area of roughly EUR 8,500/yr. Funds model a standard",
  },
  // Brazil — confidence: high. National/federal figures, 2026 tax year (minimum wage R$1,621.00; INSS teto R$8,475.55). Brazilian payroll is uniform nationwide - INSS, IRRF and FGTS are federal; there is no state/municipal wage income tax. IMPORTANT ENCODING NOTES: (1) Employee INSS is genuinely PROGRESSIVE by…
  BR: {
    code: "BR",
    name: "Brazil",
    currency: "BRL",
    subunitDivisor: 100,
    taxYear: "2025 (calendar year)",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 29145.6, rate: 0 },
        { min: 29145.6, max: 33919.8, rate: 7.5 },
        { min: 33919.8, max: 45012.6, rate: 15 },
        { min: 45012.6, max: 55976.16, rate: 22.5 },
        { min: 55976.16, max: Infinity, rate: 27.5 },
      ],
      annualAllowance: 0,
      annualRebate: 0,
    },
    funds: [
      {
        name: "INSS - Contribuicao do Segurado (employee social security / pension)",
        purpose: "pension",
        employeeRate: 14,
        employerRate: 0,
        monthlyCap: 8475.55,
        monthlyFloor: 1621,
      },
      {
        name: "INSS Patronal (employer social security / pension)",
        purpose: "pension",
        employeeRate: 0,
        employerRate: 20,
      },
      {
        name: "RAT/SAT - Seguro de Acidente de Trabalho (occupational-accident insurance)",
        purpose: "disability",
        employeeRate: 0,
        employerRate: 2,
      },
      {
        name: "FGTS - Fundo de Garantia do Tempo de Servico (severance/unemployment fund)",
        purpose: "unemployment",
        employeeRate: 0,
        employerRate: 8,
      },
      {
        name: "Sistema S / Terceiros (SENAI, SESI, SEBRAE, INCRA + Salario-Educacao)",
        purpose: "training",
        employeeRate: 0,
        employerRate: 5.8,
      },
    ],
    notes:
      "National/federal figures, 2026 tax year (minimum wage R$1,621.00; INSS teto R$8,475.55). Brazilian payroll is uniform nationwide - INSS, IRRF and FGTS are federal; there is no state/municipal wage income tax. IMPORTANT ENCODING NOTES: (1) Employee INSS is genuinely PROGRESSIVE by band on the contribution base up to the R$8,475.55/month ceiling - 7.5% up to R$1,621.00, 9% to R$2,902.84, 12% to R$4,354.27, 14% to R$8,475.55 - producing an effective max deduction of R$988.09/mo (~11.66%). The single employeeRate=14 shown is the top marginal rate; a precise engine should apply the four bands. (2) ",
  },
  // Canada (Federal) — confidence: high. Federal only. Provincial/territorial income tax (separate bracket schedules), provincial employer health/payroll levies (e.g. Ontario EHT, BC EHT, Manitoba HELevy, QC FSS), and Quebec-specific plans (QPP replaces CPP, QPIP, plus Quebec-reduced EI rate of 1.31%) are all excluded a…
  CA: {
    code: "CA",
    name: "Canada (Federal)",
    currency: "CAD",
    subunitDivisor: 100,
    taxYear: "2025 (calendar year)",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 57375, rate: 14.5 },
        { min: 57375, max: 114750, rate: 20.5 },
        { min: 114750, max: 177882, rate: 26 },
        { min: 177882, max: 253414, rate: 29 },
        { min: 253414, max: Infinity, rate: 33 },
      ],
      annualAllowance: 16129,
      annualRebate: 0,
    },
    funds: [
      {
        name: "Canada Pension Plan (CPP - base + first additional)",
        purpose: "pension",
        employeeRate: 5.95,
        employerRate: 5.95,
        monthlyCap: 5941.67,
        monthlyFloor: 291.67,
      },
      {
        name: "Canada Pension Plan second additional (CPP2)",
        purpose: "pension",
        employeeRate: 4,
        employerRate: 4,
        monthlyCap: 6766.67,
        monthlyFloor: 5941.67,
      },
      {
        name: "Employment Insurance (EI)",
        purpose: "unemployment",
        employeeRate: 1.64,
        employerRate: 2.296,
        monthlyCap: 5475,
      },
    ],
    notes:
      "Federal only. Provincial/territorial income tax (separate bracket schedules), provincial employer health/payroll levies (e.g. Ontario EHT, BC EHT, Manitoba HELevy, QC FSS), and Quebec-specific plans (QPP replaces CPP, QPIP, plus Quebec-reduced EI rate of 1.31%) are all excluded and must be added per jurisdiction of employment. Rest-of-Canada federal EI rate (1.64%) applied.",
  },
  // Russia — confidence: high. National (federal) rates — Russia has no city/regional variation in NDFL or social contributions. Assumptions: (1) Employee is a tax RESIDENT (>183 days/yr); non-residents pay flat 30% NDFL on Russian-source income (some categories 13/15). (2) NDFL bands shown apply to the ordina…
  RU: {
    code: "RU",
    name: "Russia",
    currency: "RUB",
    subunitDivisor: 100,
    taxYear: "2025 (calendar year)",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 2400000, rate: 13 },
        { min: 2400000, max: 5000000, rate: 15 },
        { min: 5000000, max: 20000000, rate: 18 },
        { min: 20000000, max: 50000000, rate: 20 },
        { min: 50000000, max: Infinity, rate: 22 },
      ],
      annualAllowance: 0,
      annualRebate: 0,
    },
    funds: [
      {
        name: "Unified social insurance contribution (\u0435\u0434\u0438\u043d\u044b\u0439 \u0442\u0430\u0440\u0438\u0444 \u2014 pension \u041e\u041f\u0421, medical \u041e\u041c\u0421, temporary disability & maternity \u0412\u041d\u0438\u041c)",
        purpose: "general",
        employeeRate: 0,
        employerRate: 30,
        monthlyCap: 248250,
      },
      {
        name: "Occupational injury & disease insurance (\u0441\u0442\u0440\u0430\u0445\u043e\u0432\u0430\u043d\u0438\u0435 \u043e\u0442 \u043d\u0435\u0441\u0447\u0430\u0441\u0442\u043d\u044b\u0445 \u0441\u043b\u0443\u0447\u0430\u0435\u0432 \u041d\u0421\u0438\u041f\u0417)",
        purpose: "disability",
        employeeRate: 0,
        employerRate: 0.2,
      },
    ],
    notes:
      "National (federal) rates \u2014 Russia has no city/regional variation in NDFL or social contributions. Assumptions: (1) Employee is a tax RESIDENT (>183 days/yr); non-residents pay flat 30% NDFL on Russian-source income (some categories 13/15). (2) NDFL bands shown apply to the ordinary salary tax base; a separate 13%/15% two-band scale applies to dividends, and to salaries of participants in the special military operation and Far-North coefficients. (3) The Unified social contribution rate is 30% up to the ANNUAL cumulative base ceiling of RUB 2,979,000 (2026, Government Resolution No. 1705 of 31.",
  },
  // Mexico — confidence: high. Federal ISR and federal IMSS/INFONAVIT/SAR contributions modeled. Contribution ceiling = 25 UMA; UMA 2025 = MXN 113.14/day, 3,439.46/month, so monthly SBC cap = MXN 85,986.50; the 3-UMA threshold (EyM excedente) = MXN 10,318.38/month. Employer CEAV rate shown is the 2025 minimum …
  MX: {
    code: "MX",
    name: "Mexico",
    currency: "MXN",
    subunitDivisor: 100,
    taxYear: "2025 (calendar year)",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 8952.49, rate: 1.92 },
        { min: 8952.49, max: 75984.55, rate: 6.4 },
        { min: 75984.55, max: 133536.07, rate: 10.88 },
        { min: 133536.07, max: 155229.8, rate: 16 },
        { min: 155229.8, max: 185852.57, rate: 17.92 },
        { min: 185852.57, max: 374837.88, rate: 21.36 },
        { min: 374837.88, max: 590795.99, rate: 23.52 },
        { min: 590795.99, max: 1127926.84, rate: 30 },
        { min: 1127926.84, max: 1503902.46, rate: 32 },
        { min: 1503902.46, max: 4511707.37, rate: 34 },
        { min: 4511707.37, max: Infinity, rate: 35 },
      ],
      annualAllowance: 0,
      annualRebate: 0,
    },
    funds: [
      {
        name: "IMSS Enfermedad y Maternidad - Cuota Fija",
        purpose: "health",
        employeeRate: 0,
        employerRate: 0,
        employeeFlatMonthly: 0,
        employerFlatMonthly: 701.65,
      },
      {
        name: "IMSS Enfermedad y Maternidad - Excedente 3 UMA",
        purpose: "health",
        employeeRate: 0.4,
        employerRate: 1.1,
        monthlyCap: 85986.5,
        monthlyFloor: 10318.38,
      },
      {
        name: "IMSS Enfermedad y Maternidad - Prestaciones en Dinero",
        purpose: "health",
        employeeRate: 0.25,
        employerRate: 0.7,
        monthlyCap: 85986.5,
      },
      {
        name: "IMSS Enfermedad y Maternidad - Gastos Medicos Pensionados",
        purpose: "health",
        employeeRate: 0.375,
        employerRate: 1.05,
        monthlyCap: 85986.5,
      },
      {
        name: "IMSS Invalidez y Vida",
        purpose: "disability",
        employeeRate: 0.625,
        employerRate: 1.75,
        monthlyCap: 85986.5,
      },
      {
        name: "IMSS Retiro (SAR)",
        purpose: "pension",
        employeeRate: 0,
        employerRate: 2,
        monthlyCap: 85986.5,
      },
      {
        name: "IMSS Cesantia en Edad Avanzada y Vejez (CEAV)",
        purpose: "pension",
        employeeRate: 1.125,
        employerRate: 3.15,
        monthlyCap: 85986.5,
      },
      {
        name: "IMSS Guarderias y Prestaciones Sociales",
        purpose: "general",
        employeeRate: 0,
        employerRate: 1,
        monthlyCap: 85986.5,
      },
      {
        name: "IMSS Riesgos de Trabajo",
        purpose: "disability",
        employeeRate: 0,
        employerRate: 0.54355,
        monthlyCap: 85986.5,
      },
      {
        name: "INFONAVIT (Housing)",
        purpose: "housing",
        employeeRate: 0,
        employerRate: 5,
        monthlyCap: 85986.5,
      },
    ],
    levies: [
      {
        name: "Impuesto Sobre Nomina (ISN) - state payroll tax (CDMX 3%)",
        rate: 3,
        paidBy: "employer",
        base: "gross",
      },
    ],
    notes:
      "Federal ISR and federal IMSS/INFONAVIT/SAR contributions modeled. Contribution ceiling = 25 UMA; UMA 2025 = MXN 113.14/day, 3,439.46/month, so monthly SBC cap = MXN 85,986.50; the 3-UMA threshold (EyM excedente) = MXN 10,318.38/month. Employer CEAV rate shown is the 2025 minimum 3.150% (for SBC up to ~1 UMA); it scales up to 6.422% for higher salaries under the 2020 pension reform's gradual increases (through 2030). Riesgos de Trabajo shown is minimum Class I premium 0.54355%; actual rate (0.5%-7.58875%) depends on the employer's risk classification/claims. The EyM Cuota Fija employer flat = 2",
  },
  // Australia — confidence: high. Federal (Commonwealth) rates. Income tax, Medicare levy, and Superannuation Guarantee are national and uniform across all states/territories. State/territory payroll tax (employer-paid, e.g. NSW 5.45%, VIC 4.85%, QLD 4.75%) is NOT included: it is levied only on employers whose to…
  AU: {
    code: "AU",
    name: "Australia",
    currency: "AUD",
    subunitDivisor: 100,
    taxYear: "1 Jul \u2013 30 Jun (FY2025-26)",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 18200, rate: 0 },
        { min: 18200, max: 45000, rate: 16 },
        { min: 45000, max: 135000, rate: 30 },
        { min: 135000, max: 190000, rate: 37 },
        { min: 190000, max: Infinity, rate: 45 },
      ],
      annualAllowance: 0,
      annualRebate: 0,
    },
    funds: [
      {
        name: "Superannuation Guarantee",
        purpose: "pension",
        employeeRate: 0,
        employerRate: 12,
        monthlyCap: 20833.33,
      },
    ],
    levies: [{ name: "Medicare Levy", rate: 2, paidBy: "employee", base: "gross" }],
    notes:
      "Federal (Commonwealth) rates. Income tax, Medicare levy, and Superannuation Guarantee are national and uniform across all states/territories. State/territory payroll tax (employer-paid, e.g. NSW 5.45%, VIC 4.85%, QLD 4.75%) is NOT included: it is levied only on employers whose total annual Australian taxable wages exceed a state-specific threshold (roughly A$700k-A$2m), so it is an employer-level obligation rather than a per-employee payroll deduction. The Medicare Levy Surcharge (1%-1.5% for high earners without private hospital cover) and Low Income Tax Offset (LITO, up to A$700, phasing out",
  },
  // South Korea — confidence: high. National rates used. Personal income tax bands are national; the 10% local income tax is a uniform surtax on national income tax nationwide (no city/province variation in rate). Rates reflect calendar-year 2025 (in effect for most of the 2025/26 period). National Pension monthly …
  KR: {
    code: "KR",
    name: "South Korea",
    currency: "KRW",
    subunitDivisor: 1,
    taxYear: "2025 (calendar year)",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 14000000, rate: 6 },
        { min: 14000000, max: 50000000, rate: 15 },
        { min: 50000000, max: 88000000, rate: 24 },
        { min: 88000000, max: 150000000, rate: 35 },
        { min: 150000000, max: 300000000, rate: 38 },
        { min: 300000000, max: 500000000, rate: 40 },
        { min: 500000000, max: 1000000000, rate: 42 },
        { min: 1000000000, max: Infinity, rate: 45 },
      ],
      annualAllowance: 1500000,
      annualRebate: 0,
    },
    funds: [
      {
        name: "National Pension (\uad6d\ubbfc\uc5f0\uae08)",
        purpose: "pension",
        employeeRate: 4.5,
        employerRate: 4.5,
        monthlyCap: 6370000,
        monthlyFloor: 400000,
      },
      {
        name: "National Health Insurance (\uac74\uac15\ubcf4\ud5d8)",
        purpose: "health",
        employeeRate: 3.545,
        employerRate: 3.545,
        monthlyCap: 119624400,
      },
      {
        name: "Long-Term Care Insurance (\uc7a5\uae30\uc694\uc591\ubcf4\ud5d8)",
        purpose: "health",
        employeeRate: 0.4591,
        employerRate: 0.4591,
        monthlyCap: 119624400,
      },
      {
        name: "Employment Insurance (\uace0\uc6a9\ubcf4\ud5d8)",
        purpose: "unemployment",
        employeeRate: 0.9,
        employerRate: 1.15,
      },
    ],
    levies: [
      {
        name: "Local Income Tax (\uc9c0\ubc29\uc18c\ub4dd\uc138)",
        rate: 10,
        paidBy: "employee",
        base: "income_tax",
      },
    ],
    notes:
      "National rates used. Personal income tax bands are national; the 10% local income tax is a uniform surtax on national income tax nationwide (no city/province variation in rate). Rates reflect calendar-year 2025 (in effect for most of the 2025/26 period). National Pension monthly contribution-base ceiling 6,370,000 and floor 400,000 apply Jul 2025\u2013Jun 2026. Health/LTC monthly contribution-base ceiling ~119,624,400 KRW is derived from the 2025 maximum monthly premium (8,481,420 total; 4,240,710/side); minor rounding vs 8,481,420\u00f77.09%\u2248119,625,106. Long-Term Care is legally 12.95% of the health p",
  },
  // Spain — confidence: high. IRPF shown is the aggregate/combined state + autonomous-community scale valid where the regional scale mirrors the state scale (PwC default reference scale). Actual total varies by autonomous community: Madrid is near the lowest (~45% top), Valencia/Catalonia highest (up to ~54% …
  ES: {
    code: "ES",
    name: "Spain",
    currency: "EUR",
    subunitDivisor: 100,
    taxYear: "2025 (calendar year)",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 12450, rate: 19 },
        { min: 12450, max: 20200, rate: 24 },
        { min: 20200, max: 35200, rate: 30 },
        { min: 35200, max: 60000, rate: 37 },
        { min: 60000, max: 300000, rate: 45 },
        { min: 300000, max: Infinity, rate: 47 },
      ],
      annualAllowance: 5550,
      annualRebate: 0,
    },
    funds: [
      {
        name: "Common contingencies (Contingencias comunes - pensions, healthcare, sickness)",
        purpose: "general",
        employeeRate: 4.7,
        employerRate: 23.6,
        monthlyCap: 4909.5,
      },
      {
        name: "Unemployment (Desempleo, indefinite/permanent contract)",
        purpose: "unemployment",
        employeeRate: 1.55,
        employerRate: 5.5,
        monthlyCap: 4909.5,
      },
      {
        name: "Vocational training (Formacion profesional)",
        purpose: "training",
        employeeRate: 0.1,
        employerRate: 0.6,
        monthlyCap: 4909.5,
      },
      {
        name: "Intergenerational Equity Mechanism (MEI)",
        purpose: "pension",
        employeeRate: 0.13,
        employerRate: 0.67,
        monthlyCap: 4909.5,
      },
      {
        name: "Wage Guarantee Fund (FOGASA)",
        purpose: "general",
        employeeRate: 0,
        employerRate: 0.2,
        monthlyCap: 4909.5,
      },
      {
        name: "Occupational accidents & diseases (AT/EP, employer-only, rate varies by activity tariff; representative avg)",
        purpose: "disability",
        employeeRate: 0,
        employerRate: 1.5,
        monthlyCap: 4909.5,
      },
    ],
    notes:
      "IRPF shown is the aggregate/combined state + autonomous-community scale valid where the regional scale mirrors the state scale (PwC default reference scale). Actual total varies by autonomous community: Madrid is near the lowest (~45% top), Valencia/Catalonia highest (up to ~54% top). Social security rates and the EUR 4,909.50/month (EUR 58,914/yr over 12) contribution-base ceiling are national/uniform for 2025. Occupational-accident (AT/EP) rate is employer-only and varies by activity risk tariff (~0.99%-7.15%); 1.50% used as a representative average. A tiered solidarity surcharge (starting 0",
  },
  // Indonesia — confidence: high. Jakarta (DKI Jakarta) assumed. Indonesia's PPh 21 income tax and BPJS contribution rates are set nationally and do not vary by province. Sub-national variation is limited to the minimum wage (UMP/UMK) used as the BPJS wage floor: the DKI Jakarta 2025 UMP of IDR 5,396,761/month is…
  ID: {
    code: "ID",
    name: "Indonesia",
    currency: "IDR",
    subunitDivisor: 100,
    taxYear: "2025 (calendar year)",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 60000000, rate: 5 },
        { min: 60000000, max: 250000000, rate: 15 },
        { min: 250000000, max: 500000000, rate: 25 },
        { min: 500000000, max: 5000000000, rate: 30 },
        { min: 5000000000, max: Infinity, rate: 35 },
      ],
      annualAllowance: 54000000,
      annualRebate: 0,
    },
    funds: [
      {
        name: "BPJS Ketenagakerjaan - JHT (Jaminan Hari Tua / Old-Age Savings)",
        purpose: "pension",
        employeeRate: 2,
        employerRate: 3.7,
      },
      {
        name: "BPJS Ketenagakerjaan - JP (Jaminan Pensiun / Pension)",
        purpose: "pension",
        employeeRate: 1,
        employerRate: 2,
        monthlyCap: 11086300,
      },
      {
        name: "BPJS Kesehatan (National Health Insurance / JKN)",
        purpose: "health",
        employeeRate: 1,
        employerRate: 4,
        monthlyCap: 12000000,
        monthlyFloor: 5396761,
      },
      {
        name: "BPJS Ketenagakerjaan - JKK (Jaminan Kecelakaan Kerja / Work Accident)",
        purpose: "disability",
        employeeRate: 0,
        employerRate: 0.24,
      },
      {
        name: "BPJS Ketenagakerjaan - JKM (Jaminan Kematian / Death Benefit)",
        purpose: "disability",
        employeeRate: 0,
        employerRate: 0.3,
      },
      {
        name: "BPJS Ketenagakerjaan - JKP (Jaminan Kehilangan Pekerjaan / Unemployment)",
        purpose: "unemployment",
        employeeRate: 0,
        employerRate: 0,
        monthlyCap: 5000000,
      },
    ],
    notes:
      "Jakarta (DKI Jakarta) assumed. Indonesia's PPh 21 income tax and BPJS contribution rates are set nationally and do not vary by province. Sub-national variation is limited to the minimum wage (UMP/UMK) used as the BPJS wage floor: the DKI Jakarta 2025 UMP of IDR 5,396,761/month is used as the BPJS Kesehatan contribution floor and should be refreshed to the current-year regional minimum wage (batas bawah = UMK). JKK employer rate 0.24% reflects the lowest of five industry risk-class bands (0.24%-1.74%); adjust to the employer's actual risk class. JKP total contribution is 0.46% of wages (capped ",
  },
  // Saudi Arabia — confidence: high. National GOSI rates for SAUDI NATIONALS (no sub-national/city variation in Saudi Arabia). Numeric fields reflect the EXISTING social-insurance system (subscribers who began contributing before 3 July 2024): pension/annuities 9% employee + 9% employer, SANED 0.75% each, occupation…
  SA: {
    code: "SA",
    name: "Saudi Arabia",
    currency: "SAR",
    subunitDivisor: 100,
    taxYear: "2025 (calendar year)",
    incomeTax: {
      system: "none",
      annualBands: [],
      annualAllowance: 0,
      annualRebate: 0,
    },
    funds: [
      {
        name: "GOSI Annuities (Pension / Retirement)",
        purpose: "pension",
        employeeRate: 9,
        employerRate: 9,
        monthlyCap: 45000,
      },
      {
        name: "GOSI SANED (Unemployment Insurance)",
        purpose: "unemployment",
        employeeRate: 0.75,
        employerRate: 0.75,
        monthlyCap: 45000,
      },
      {
        name: "GOSI Occupational Hazards (Work Injury / Disability)",
        purpose: "disability",
        employeeRate: 0,
        employerRate: 2,
        monthlyCap: 45000,
      },
    ],
    notes:
      "National GOSI rates for SAUDI NATIONALS (no sub-national/city variation in Saudi Arabia). Numeric fields reflect the EXISTING social-insurance system (subscribers who began contributing before 3 July 2024): pension/annuities 9% employee + 9% employer, SANED 0.75% each, occupational hazards 2% employer only (total 21.5%). Under the reformed system operationally effective 3 July 2025, NEW entrants (no prior contribution period before 3 July 2024) pay a higher annuities rate of 9.5% employee + 9.5% employer in 2025/26, rising 0.5%/yr each side to 11% each by July 2028; SANED and occupational-haza",
  },
  // Türkiye — confidence: high. Uniform national rates — Türkiye has no sub-national (provincial/municipal) income-tax or social-security rate variation. Income tax bands are the 2025 WAGE-income brackets (27% band extends to 1,200,000 TRY for wages vs 800,000 for non-wage income). annualAllowance = annual gros…
  TR: {
    code: "TR",
    name: "T\u00fcrkiye",
    currency: "TRY",
    subunitDivisor: 100,
    taxYear: "2025 (calendar year)",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 158000, rate: 15 },
        { min: 158000, max: 330000, rate: 20 },
        { min: 330000, max: 1200000, rate: 27 },
        { min: 1200000, max: 4300000, rate: 35 },
        { min: 4300000, max: Infinity, rate: 40 },
      ],
      annualAllowance: 312066,
      annualRebate: 0,
    },
    funds: [
      {
        name: "Pension, Disability & Death Insurance (Malull\u00fck, Ya\u015fl\u0131l\u0131k ve \u00d6l\u00fcm Sigortas\u0131)",
        purpose: "pension",
        employeeRate: 9,
        employerRate: 11,
        monthlyCap: 195041.4,
        monthlyFloor: 26005.5,
      },
      {
        name: "General Health Insurance (Genel Sa\u011fl\u0131k Sigortas\u0131)",
        purpose: "health",
        employeeRate: 5,
        employerRate: 7.5,
        monthlyCap: 195041.4,
        monthlyFloor: 26005.5,
      },
      {
        name: "Short-Term Insurance \u2013 Work Accident & Occupational Disease (K\u0131sa Vadeli Sigorta Kollar\u0131)",
        purpose: "disability",
        employeeRate: 0,
        employerRate: 2,
        monthlyCap: 195041.4,
        monthlyFloor: 26005.5,
      },
      {
        name: "Unemployment Insurance (\u0130\u015fsizlik Sigortas\u0131)",
        purpose: "unemployment",
        employeeRate: 1,
        employerRate: 2,
        monthlyCap: 195041.4,
        monthlyFloor: 26005.5,
      },
    ],
    levies: [{ name: "Stamp Tax (Damga Vergisi)", rate: 0.759, paidBy: "employee", base: "gross" }],
    notes:
      "Uniform national rates \u2014 T\u00fcrkiye has no sub-national (provincial/municipal) income-tax or social-security rate variation. Income tax bands are the 2025 WAGE-income brackets (27% band extends to 1,200,000 TRY for wages vs 800,000 for non-wage income). annualAllowance = annual gross minimum wage (26,005.50 \u00d7 12 = 312,066 TRY): since 2022 the minimum-wage portion of every salary is exempt from income tax AND stamp tax (implemented monthly by deducting the tax computed on the minimum wage). Modeling this as a full gross-minimum-wage allowance is an approximation that correctly yields zero income t",
  },
  // Switzerland (Zurich canton) — confidence: high. Zurich canton (city of Zurich). MODELLING NOTES: (1) Income tax shown is ONLY the federal direct tax (direkte Bundessteuer) single-person schedule, uniform nationwide. The larger cantonal + communal income tax is levied separately (base tariff x annual multipliers, Zurich canton …
  CH: {
    code: "CH",
    name: "Switzerland (Zurich canton)",
    currency: "CHF",
    subunitDivisor: 100,
    taxYear: "2025 (calendar year)",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 15200, rate: 0 },
        { min: 15200, max: 33200, rate: 0.77 },
        { min: 33200, max: 43500, rate: 0.88 },
        { min: 43500, max: 58000, rate: 2.64 },
        { min: 58000, max: 76200, rate: 2.97 },
        { min: 76200, max: 82100, rate: 5.94 },
        { min: 82100, max: 108900, rate: 6.6 },
        { min: 108900, max: 141500, rate: 8.8 },
        { min: 141500, max: 185100, rate: 11 },
        { min: 185100, max: 793900, rate: 13.2 },
        { min: 793900, max: Infinity, rate: 11.5 },
      ],
      annualAllowance: 0,
      annualRebate: 0,
    },
    funds: [
      {
        name: "AHV/IV/EO (OASI/DI/Income Compensation, 1st pillar)",
        purpose: "pension",
        employeeRate: 5.3,
        employerRate: 5.3,
      },
      {
        name: "ALV (Unemployment Insurance)",
        purpose: "unemployment",
        employeeRate: 1.1,
        employerRate: 1.1,
        monthlyCap: 12350,
      },
      {
        name: "BVG/LPP occupational pension (2nd pillar, mandatory)",
        purpose: "pension",
        employeeRate: 5,
        employerRate: 5,
        monthlyCap: 7560,
        monthlyFloor: 1890,
      },
      {
        name: "UVG/LAA non-occupational accident (NBU, employee-paid)",
        purpose: "health",
        employeeRate: 1.6,
        employerRate: 0,
        monthlyCap: 12350,
      },
      {
        name: "UVG/LAA occupational accident (BU, employer-paid)",
        purpose: "health",
        employeeRate: 0,
        employerRate: 0.17,
        monthlyCap: 12350,
      },
      {
        name: "Family Allowance fund (FAK/Familienzulagen, Zurich)",
        purpose: "general",
        employeeRate: 0,
        employerRate: 1.2,
      },
    ],
    notes:
      "Zurich canton (city of Zurich). MODELLING NOTES: (1) Income tax shown is ONLY the federal direct tax (direkte Bundessteuer) single-person schedule, uniform nationwide. The larger cantonal + communal income tax is levied separately (base tariff x annual multipliers, Zurich canton ~98% + city ~119% for 2025) and is NOT withheld through payroll for Swiss nationals / C-permit holders (assessed and billed directly). (2) For foreign employees without a C permit the employer withholds cantonal source tax (Quellensteuer) per Zurich tariff codes A-H, replacing the bands above. (3) Mandatory health insu",
  },
  // Netherlands — confidence: high. Netherlands has no sub-national (municipal/provincial) income tax or social security; all rates are national. Figures are 2025, for employees below AOW state-pension age. incomeTax.annualBands show the WAGE-TAX-ONLY component (loonbelasting): the official combined Box 1 rates are…
  NL: {
    code: "NL",
    name: "Netherlands",
    currency: "EUR",
    subunitDivisor: 100,
    taxYear: "2025 (calendar year)",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 38441, rate: 8.17 },
        { min: 38441, max: 76817, rate: 37.48 },
        { min: 76817, max: Infinity, rate: 49.5 },
      ],
      annualAllowance: 0,
      annualRebate: 3068,
    },
    funds: [
      {
        name: "AOW - state old-age pension (national insurance)",
        purpose: "pension",
        employeeRate: 17.9,
        employerRate: 0,
        monthlyCap: 3203.42,
      },
      {
        name: "Anw - surviving dependants (national insurance)",
        purpose: "general",
        employeeRate: 0.1,
        employerRate: 0,
        monthlyCap: 3203.42,
      },
      {
        name: "Wlz - long-term care (national insurance)",
        purpose: "health",
        employeeRate: 9.65,
        employerRate: 0,
        monthlyCap: 3203.42,
      },
      {
        name: "Awf - unemployment fund (WW, low rate / permanent contract)",
        purpose: "unemployment",
        employeeRate: 0,
        employerRate: 2.74,
        monthlyCap: 6322,
      },
      {
        name: "Aof - disability fund (differentiated, high rate / medium-large employer)",
        purpose: "disability",
        employeeRate: 0,
        employerRate: 7.64,
        monthlyCap: 6322,
      },
      {
        name: "Whk - return-to-work fund (Werkhervattingskas, sector average)",
        purpose: "disability",
        employeeRate: 0,
        employerRate: 1.33,
        monthlyCap: 6322,
      },
      {
        name: "Zvw - health insurance income-dependent contribution (employer, high rate)",
        purpose: "health",
        employeeRate: 0,
        employerRate: 6.51,
        monthlyCap: 6322,
      },
      {
        name: "Wko - childcare surcharge (Opslag kinderopvang, part of Aof)",
        purpose: "general",
        employeeRate: 0,
        employerRate: 0.5,
        monthlyCap: 6322,
      },
    ],
    notes:
      "Netherlands has no sub-national (municipal/provincial) income tax or social security; all rates are national. Figures are 2025, for employees below AOW state-pension age. incomeTax.annualBands show the WAGE-TAX-ONLY component (loonbelasting): the official combined Box 1 rates are 35.82% / 37.48% / 49.50%, but bracket 1's 27.65% national-insurance component (AOW 17.90% + Anw 0.10% + Wlz 9.65%) is broken out separately under funds to avoid double-counting, leaving 35.82% - 27.65% = 8.17% as pure wage tax in bracket 1 (brackets 2 and 3 carry no national insurance since its base is capped at the b",
  },
  // Singapore — confidence: high. Tax year YA2025/2026 for income tax; CPF & SDL at statutory rates in force from 1 Jan 2026 (verified July 2026).
  SG: {
    code: "SG",
    name: "Singapore",
    currency: "SGD",
    subunitDivisor: 100,
    taxYear: "YA2025/2026 (CPF & SDL: statutory rates in force from 1 Jan 2026)",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 20000, rate: 0 },
        { min: 20000, max: 30000, rate: 2 },
        { min: 30000, max: 40000, rate: 3.5 },
        { min: 40000, max: 80000, rate: 7 },
        { min: 80000, max: 120000, rate: 11.5 },
        { min: 120000, max: 160000, rate: 15 },
        { min: 160000, max: 200000, rate: 18 },
        { min: 200000, max: 240000, rate: 19 },
        { min: 240000, max: 280000, rate: 19.5 },
        { min: 280000, max: 320000, rate: 20 },
        { min: 320000, max: 500000, rate: 22 },
        { min: 500000, max: 1000000, rate: 23 },
        { min: 1000000, max: Infinity, rate: 24 },
      ],
      annualAllowance: 0,
      annualRebate: 0,
    },
    funds: [
      {
        name: "Central Provident Fund (CPF)",
        purpose: "pension",
        employeeRate: 20,
        employerRate: 17,
        monthlyCap: 8000,
      },
      {
        name: "Skills Development Levy (SDL)",
        purpose: "training",
        employeeRate: 0,
        employerRate: 0.25,
        monthlyCap: 4500,
      },
    ],
    notes:
      "Tax year YA2025/2026 for income tax; CPF & SDL at statutory rates in force from 1 Jan 2026 (verified July 2026). INCOME TAX: resident progressive schedule confirmed against IRAS and PwC Worldwide Tax Summaries \u2014 0% on first S$20,000 rising to a 24% top band above S$1,000,000; this schedule has applied unchanged from YA2024 through YA2026. The first S$20,000 is modelled as a 0% band (annualAllowance=0), NOT double-counted. Bands apply to CHARGEABLE income; personal reliefs/deductions (earned income, spouse, child, CPF relief, etc.) are NOT modelled, so real resident tax is typically lower. NON-RESIDENTS are taxed differently (employment income at higher of 15% flat or resident rates; other income generally 24%) and are NOT covered. A one-off Personal Income Tax Rebate applied \u2014 YA2025: 60% of tax payable capped at S$200 (YA2024: 50% capped S$200); because it is percentage-based and capped it does not fit the flat annualRebate field, so annualRebate=0 and actual resident tax may be marginally lower for mid earners. CPF: employee 20% + employer 17% (age \u226455) on the Ordinary Wage ceiling of S$8,000/month, the final value in the phased roadmap (S$6,800 in 2024, S$7,400 in 2025, S$8,000 from 1 Jan 2026) \u2014 modelled as monthlyCap=8000; the Additional Wage (bonus) ceiling and its annual-total mechanics are not modelled. CPF is mandatory ONLY for Singapore Citizens and Permanent Residents; foreign/work-pass holders are exempt (per convention the national statutory rate is still modelled, as with Saudi GOSI). CPF rates step DOWN with age (>55\u201360: employee 18%/employer 16%; 60\u201365: 12.5%/12.5%; 65\u201370: 7.5%/9%; >70: 5%/7.5%) and PRs pay graduated first-/second-year rates \u2014 only the full age-\u226455 rate is modelled. Low-wage graduated CPF (no/partial employee share for total wages \u2264S$750/month) is not modelled. CPF is classified purpose='pension' but is a comprehensive statutory savings scheme also funding healthcare (Medisave) and housing. SDL (Skills Development Levy): employer-only, 0.25% of monthly wages on the first S$4,500 (employerRate 0.25, monthlyCap 4500), giving a max of S$11.25/employee; the S$2 minimum for employees earning <S$800/month is not captured by the linear model. SDL applies to ALL employees working in Singapore including foreigners (unlike CPF). Singapore has NO statutory national minimum wage (only sector-specific Progressive Wage Model floors, not modelled). All monetary values in major units (SGD); subunitDivisor=100.",
  },
  // United Arab Emirates — confidence: high. Tax year 2025/26.
  AE: {
    code: "AE",
    name: "United Arab Emirates",
    currency: "AED",
    subunitDivisor: 100,
    taxYear: "2025/26",
    incomeTax: {
      system: "none",
      annualBands: [],
      annualAllowance: 0,
      annualRebate: 0,
    },
    funds: [
      {
        name: "GPSSA Pension & Social Security",
        purpose: "pension",
        employeeRate: 5,
        employerRate: 12.5,
        monthlyCap: 50000,
        monthlyFloor: 1000,
      },
      {
        name: "ILOE Unemployment Insurance",
        purpose: "unemployment",
        employeeRate: 0,
        employerRate: 0,
        employeeFlatMonthly: 5,
      },
    ],
    notes:
      "Tax year 2025/26. The UAE levies NO personal income tax on employment income (incomeTax.system='none'; independently confirmed via PwC Worldwide Tax Summaries and multiple 2026 sources) \u2014 the only individual-facing statutory monthly payroll items are GPSSA social-security pension and the ILOE unemployment premium. GPSSA pension applies to UAE/GCC NATIONALS ONLY; non-GCC expatriate/foreign employees pay NO monthly social security and instead accrue an end-of-service gratuity (EOSB) that is an EMPLOYER liability paid on termination, not a monthly deduction, so it is deliberately NOT modelled as a fund \u2014 expat employees therefore have ZERO fund contributions except the flat ILOE premium below. Two GPSSA regimes coexist: (1) OLD law (Federal Law No. 7 of 1999) governs nationals first registered BEFORE 31 Oct 2023 (still the majority of employed nationals): private-sector total 20% of the contribution-calculation salary = employee 5% + employer 12.5% + government 2.5% (the government pays the 2.5% as an Emiratisation subsidy so it is NOT an employer cost), with the contribution salary floored at AED 1,000 and capped at AED 50,000/month. This is exactly what the funds block models (employeeRate 5, employerRate 12.5 = net employer cost, floor 1,000, cap 50,000) because it is PwC's headline UAE rate and covers most current national employees; the 2.5% government share is correctly excluded from employerRate. (2) NEW law (Federal Decree-Law No. 57 of 2023, effective 31 Oct 2023, contributions payable from 1 Jan 2024) applies only to nationals entering the workforce for the FIRST time on/after that date: total 26% = employee 11% + employer 15%, with the government still subsidising 2.5% of the employer share for those earning under AED 20,000 (net employer 12.5% below that threshold), and the private-sector contribution-salary cap raised to AED 70,000/month (public-sector cap AED 100,000/month; floor still AED 1,000). Payroll for post-31-Oct-2023 first-time national hires should use employee 11% / employer 15% and cap 70,000 in place of the modelled old-law figures. Abu Dhabi nationals fall under a separate scheme (ADPF) \u2014 per PwC employee 5% / employer 15% / government 6% = 26%, cap up to AED 100,000 for new members \u2014 not modelled here. ILOE (Involuntary Loss of Employment) insurance is mandatory for ALL private-sector and federal-government employees, BOTH nationals and expatriate residents, and is EMPLOYEE-paid as a flat premium: AED 5/month where basic salary <= AED 16,000, or AED 10/month where basic salary > AED 16,000 (VAT is added on top). Modelled as employeeFlatMonthly = 5 (the representative lower tier, since most basic salaries are below AED 16,000); use AED 10/month for higher earners. ILOE exemptions: business owners/investors, domestic workers, temporary-contract workers, under-18s, and pensioned retirees who take new jobs. No income-tax-based levies exist (the UAE's 5% VAT and 9% corporate tax are not employee payroll levies). All load-bearing numbers were independently re-verified against current 2025/26 sources \u2014 no income tax; GPSSA old-law 5%/12.5%(+2.5% gov), floor AED 1,000, cap AED 50,000; new-law 11%/15%, cap AED 70,000; ILOE AED 5/10 at the AED 16,000 line \u2014 confidence high.",
  },
  // Sweden — confidence: high. Income year 2026 (Sweden's tax year is the calendar year; figures current as of July 2026).
  SE: {
    code: "SE",
    name: "Sweden",
    currency: "SEK",
    subunitDivisor: 100,
    taxYear: "2026",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 643000, rate: 32.38 },
        { min: 643000, max: Infinity, rate: 52.38 },
      ],
      annualAllowance: 17400,
      annualRebate: 48000,
    },
    funds: [
      {
        name: "Arbetsgivaravgifter (employer social security contributions)",
        purpose: "general",
        employeeRate: 0,
        employerRate: 31.42,
      },
    ],
    notes:
      "Income year 2026 (Sweden's tax year is the calendar year; figures current as of July 2026). Income tax = flat municipal tax + a single 20% national/state bracket on taxable earned income above the skiktgraens of SEK 643,000 (2025 was SEK 625,800); the pre-2020 top 'vaernskatt' is abolished, so state tax is one 20% bracket. Band-1 rate 32.38% is the SCB 2026 population-weighted AVERAGE total local rate (kommun + region); actual rates range 28.93% (Oesteraaker) to 35.65% (Dorotea), so effective tax varies by municipality. Top marginal 52.38% = 32.38% + 20%. annualAllowance = SEK 17,400 = the grundavdrag FLOOR (high-income minimum); grundavdrag is income-dependent and rises to ~SEK 45,600 for low/mid incomes, so pre-credit tax is somewhat overstated for lower earners (offset by the rebate). Using 17,400 makes the state-tax breakpoint equal the official 2026 brytpunkt (gross SEK 660,400 = 643,000 + 17,400, under-66). annualRebate = SEK 48,000 is a FLAT proxy for the earned-income tax credits: the 2026 jobbskatteavdrag maxes at ~SEK 52,392/yr (~4,366/mo, plateau reached ~40,000/mo gross; the high-income phase-out was abolished from 2025) plus the skattereduktion foer foervaervsinkomster. The flat value is calibrated against Skatteverket's official 2026 monthly withholding table (SKV table 32, column 1) so modelled net pay is within ~1-2% of the table across ~30,000-70,000/mo gross (30k->~24.8k net, 45k->~34.9k, 60k->~44.0k). Because the real credit phases IN below ~40,000/mo, net is slightly OVERstated for low earners (~+2% at 30k) and marginally understated at high incomes; a single flat rebate cannot capture the phase-in exactly. Employer social security (arbetsgivaravgifter) = 31.42% of gross with NO ceiling (2026 composition: old-age pension 10.21%, survivors 0.30%, sickness 3.55%, parental 2.00%, labour-market 2.64%, work-injury 0.10%, general payroll tax 12.62%). NOT modelled: reduced 10.21% employer rate for employees 67+ (from 2026), the temporary youth reduction to 20.81% for ages 19-23 (Apr 2026-Sep 2027), and the reduced ~20.81% rate on the first SEK 25,000/mo that certain small employers apply. The employee general pension contribution (allmaen pensionsavgift) is 7% of earned income up to a base ceiling of SEK 673,038/yr (8.07 x income base amount SEK 83,400; max fee ~SEK 47,100), BUT it is 100% offset by a matching tax reduction (already reflected in the withholding table), so it has essentially no effect on net pay and is deliberately OMITTED from employee funds. Church fee (~1%, church members only) and burial fee (~0.25%) are not modelled. Non-resident SINK flat tax (25%; 22.5% at source on employment income from 2026, dropping to 20% in 2027) and 66+/67+ special allowances are out of scope. Load-bearing numbers (state rate 20% / skiktgraens SEK 643,000, average local rate 32.38%, employer 31.42% uncapped, employee pension 7% cap SEK 673,038, grundavdrag floor 17,400, brytpunkt SEK 660,400) confirmed against Skatteverket (2026 belopp/procent, tax table 32, employer contributions), SCB local taxes 2026, PwC and regeringen.se.",
  },
  // Ireland — confidence: high. Ireland 2026 CALENDAR tax year (Ireland uses a Jan-Dec year, not April-April).
  IE: {
    code: "IE",
    name: "Ireland",
    currency: "EUR",
    subunitDivisor: 100,
    taxYear: "2026",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 44000, rate: 20 },
        { min: 44000, max: Infinity, rate: 40 },
      ],
      annualAllowance: 0,
      annualRebate: 4000,
    },
    funds: [
      {
        name: "Pay Related Social Insurance (PRSI) - Class A",
        purpose: "general",
        employeeRate: 4.2,
        employerRate: 11.25,
      },
    ],
    levies: [{ name: "Universal Social Charge (USC)", rate: 2, paidBy: "employee", base: "gross" }],
    notes:
      "Ireland 2026 CALENDAR tax year (Ireland uses a Jan-Dec year, not April-April). All load-bearing numbers independently re-verified July 2026 against KPMG Budget 2026 tables, Revenue.ie, and Citizens Information; Budget 2026 (announced Oct 2025) left income-tax bands and tax credits UNCHANGED from 2025. INCOME TAX: single-person standard-rate band EUR 44,000 taxed at 20%, balance at 40%. Ireland grants tax CREDITS not allowances, so annualAllowance=0 and annualRebate=EUR 4,000 = personal credit (EUR 2,000) + PAYE/employee credit (EUR 2,000), the standard combination for a single PAYE employee; a self-employed person would instead use the EUR 2,000 earned-income credit, which does NOT stack with the PAYE credit. Worked check: gross EUR 44,000 -> 20% x 44,000 = 8,800 tax, minus 4,000 credit = EUR 4,800/yr (EUR 400/mo). Credits are non-refundable (kernel clamps tax to >=0), matching reality for low earners. USC is genuinely PROGRESSIVE (2026 bands: 0.5% to EUR 12,012; 2% on 12,012-28,700; 3% on 28,700-70,044; 8% above 70,044; plus a 3% self-employed surcharge on income over EUR 100,000; FULL EXEMPTION where annual income is EUR 13,000 or less), but the engine supports only a flat levy, so USC is APPROXIMATED as a flat 2.0% of gross - the effective USC rate for an average full-time salary (EUR 44k gives ~1.94%, EUR 50k ~2.07%). This flat 2.0% UNDERSTATES USC for high earners (8% marginal above EUR 70,044) and OVERSTATES it for low earners and anyone under the EUR 13,000 exemption; reduced USC rates (0.5% then 2%) also apply to over-70s / full medical-card holders earning EUR 60,000 or less. PRSI: modelled as a single general Social-Insurance-Fund contribution (bundling pension, jobseeker, illness and other benefits) at Class A1 rates in force from 1 Jan 2026 - employee 4.20% and employer 11.25% of gross, UNCAPPED (no earnings ceiling on either side, so no monthly cap). Both PRSI rates rise 0.15% on 1 OCTOBER 2026 to 4.35% (employee) and 11.40% (employer); the pre-October rates are modelled here as the config's as-of date is July 2026. Two PRSI thresholds the flat-rate engine cannot capture: (1) employees earning EUR 352/week or less pay 0% employee PRSI, with a tapered PRSI credit just above that line; (2) the employer rate is a reduced 9.0% (9.15% from 1 Oct 2026) for weekly earnings of EUR 552 or less rather than 11.25% - the 11.25% modelled applies to typical full-time earners above that threshold. The employer PRSI rate is INCLUSIVE of the National Training Fund levy (not a separate line item). All figures are for standard Class A1 (private-sector employees); public-sector and modified-rate PRSI classes differ.",
  },
  // Poland — confidence: high. Tax year modelled = 2026 (Polish tax year = calendar year); mid-2026 statutory figures, independently reconfirmed against ZUS official (lang.zus.pl), PwC Worldwide Tax Summaries, OECD Taxing Wages 2026, and multiple 2026 payroll providers.
  PL: {
    code: "PL",
    name: "Poland",
    currency: "PLN",
    subunitDivisor: 100,
    taxYear: "2026",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 120000, rate: 12 },
        { min: 120000, max: Infinity, rate: 32 },
      ],
      annualAllowance: 0,
      annualRebate: 3600,
    },
    funds: [
      {
        name: "Old-age pension (emerytalne)",
        purpose: "pension",
        employeeRate: 9.76,
        employerRate: 9.76,
        monthlyCap: 23550,
      },
      {
        name: "Disability pension (rentowe)",
        purpose: "disability",
        employeeRate: 1.5,
        employerRate: 6.5,
        monthlyCap: 23550,
      },
      {
        name: "Sickness insurance (chorobowe)",
        purpose: "general",
        employeeRate: 2.45,
        employerRate: 0,
      },
      {
        name: "Health insurance (NFZ, skladka zdrowotna)",
        purpose: "health",
        employeeRate: 9,
        employerRate: 0,
      },
      {
        name: "Accident insurance (wypadkowe)",
        purpose: "disability",
        employeeRate: 0,
        employerRate: 1.67,
      },
      {
        name: "Labour Fund + Solidarity Fund (Fundusz Pracy)",
        purpose: "unemployment",
        employeeRate: 0,
        employerRate: 2.45,
      },
      {
        name: "Guaranteed Employee Benefits Fund (FGSP)",
        purpose: "general",
        employeeRate: 0,
        employerRate: 0.1,
      },
    ],
    notes:
      "Tax year modelled = 2026 (Polish tax year = calendar year); mid-2026 statutory figures, independently reconfirmed against ZUS official (lang.zus.pl), PwC Worldwide Tax Summaries, OECD Taxing Wages 2026, and multiple 2026 payroll providers. PIT scale is identical to 2025: progressive 12% on annual base up to PLN 120,000 and 32% on the excess, with a PLN 30,000 tax-free amount. Poland implements the tax-free amount as a flat annual tax-reducing credit (kwota zmniejszajaca podatek) of PLN 3,600 (=12% x 30,000), NOT a base deduction, so it is modelled as annualRebate=3600 with annualAllowance=0 to preserve the real PLN 120,000 band boundary (tax at 120,000 = 12% x 120,000 - 3,600 = 10,800, matching the published figure; an equivalent encoding would be annualAllowance=30,000 with band edges 90,000/1e12 and no rebate). The PLN 3,600 credit is flat for all scale taxpayers (not phased out). ZUS social-security rates are unchanged 2025->2026; only the pension/disability contribution-base ceiling (30x projected average monthly wage) rose from PLN 260,190 in 2025 (30 x 8,673; monthly 21,682.50) to PLN 282,600 in 2026 (30 x 9,420; monthly 23,550.00) \u2014 the monthlyCap of 23,550 encodes the 2026 value (switch to 21,682.50 for a 2025 run). Employee ZUS: pension 9.76% + disability 1.5% + sickness 2.45% (=13.71%); pension and disability stop once cumulative annual earnings pass the cap (approximated here as a monthlyCap of 23,550 \u2014 exact for steady monthly pay, an approximation of the true year-to-date cumulative cap), while sickness is UNCAPPED. Health insurance (NFZ) is 9%, uncapped, and \u2014 critically since the 2022 Polski Lad reform \u2014 NOT deductible from PIT. Employer ZUS: pension 9.76% + disability 6.5% + accident (wypadkowe) 1.67% + Labour/Solidarity Fund 2.45% + FGSP 0.10%, a typical total employer load of ~19.21%-22.41% of gross. APPROXIMATIONS/CAVEATS: (1) Accident insurance 1.67% is the representative default for small payers (<10 insured) \u2014 it varies by industry risk from 0.67% to 3.33% and is individually assigned for larger employers. (2) The compute kernel derives PIT from gross x 12; the real Polish PIT base excludes the employee's deductible social-security contributions (~13.71%) and cost-of-earning deductions, so this config slightly OVERSTATES income tax versus an exact payroll \u2014 funds are computed correctly on gross. (3) No monthlyFloor is set: statutory ZUS bases cannot fall below the full-time minimum wage (PLN 4,666/mo in 2025, PLN 4,806/mo in 2026), but that floor is pro-rated for part-timers, so a flat floor would wrongly inflate contributions for legitimate part-month/part-time pay. (4) Labour Fund/FGSP are not due on bases below the minimum wage and are waived for employees over state pension age (women 60/men 65) \u2014 not modelled. (5) Not modelled as a levy: the 4% solidarity levy (danina solidarnosciowa) applying only to annual income above PLN 1,000,000. Eligibility: these are the standard national employment-contract (umowa o prace) rates and apply to all such employees regardless of nationality; civil-law contracts, self-employed/entrepreneur flat bases, and Small ZUS Plus follow different rules not covered here.",
  },
  // Philippines — confidence: high. Tax year 2025 (rates identical for 2026 — all three statutory funds reached their final legislated phase in 2025 with no further increases scheduled, and the TRAIN income-tax schedule is permanent from 1 Jan 2023 onward, independently confirmed via PwC Worldwide Tax Summaries).
  PH: {
    code: "PH",
    name: "Philippines",
    currency: "PHP",
    subunitDivisor: 100,
    taxYear: "2025-2026",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 250000, rate: 0 },
        { min: 250000, max: 400000, rate: 15 },
        { min: 400000, max: 800000, rate: 20 },
        { min: 800000, max: 2000000, rate: 25 },
        { min: 2000000, max: 8000000, rate: 30 },
        { min: 8000000, max: Infinity, rate: 35 },
      ],
      annualAllowance: 0,
      annualRebate: 0,
    },
    funds: [
      {
        name: "Social Security System (SSS)",
        purpose: "pension",
        employeeRate: 5,
        employerRate: 10,
        monthlyCap: 35000,
        monthlyFloor: 5000,
        employerFlatMonthly: 30,
      },
      {
        name: "PhilHealth (National Health Insurance)",
        purpose: "health",
        employeeRate: 2.5,
        employerRate: 2.5,
        monthlyCap: 100000,
        monthlyFloor: 10000,
      },
      {
        name: "Pag-IBIG Fund (HDMF)",
        purpose: "housing",
        employeeRate: 2,
        employerRate: 2,
        monthlyCap: 10000,
      },
    ],
    notes:
      "Tax year 2025 (rates identical for 2026 \u2014 all three statutory funds reached their final legislated phase in 2025 with no further increases scheduled, and the TRAIN income-tax schedule is permanent from 1 Jan 2023 onward, independently confirmed via PwC Worldwide Tax Summaries). INCOME TAX: TRAIN Law (RA 10963) graduated annual schedule modelled as marginal bands with the 0% exemption expressed as the first band (0\u2013250,000 at 0%), so annualAllowance is not used (avoids double-counting). Top marginal rate 35% above PHP 8,000,000; top-band max set to 1e12 per engine convention. Applies to resident citizens/aliens on compensation income; no separate personal/basic allowance exists. NOT modelled: the optional 8% flat gross-income tax for self-employed/professionals under the PHP 3M VAT threshold (not relevant to employed payroll); the PHP 90,000 tax-exempt cap on 13th-month pay and other benefits; and de minimis benefits \u2014 the kernel taxes gross monthly*12, so 13th-month/de-minimis exemptions are not reflected. CAVEAT: mandatory employee SSS/PhilHealth/Pag-IBIG contributions are legally deductible from taxable compensation before applying the TRAIN table, but the kernel has no field to subtract them, so modelled income tax is slightly overstated for most earners. SSS (RA 11199, Circular 2024-006): contribution rate reached its final 15% phase on 1 Jan 2025 (employee 5% / employer 10%) on Monthly Salary Credit with floor PHP 5,000 and ceiling PHP 35,000 \u2014 employee max PHP 1,750/mo, employer max PHP 3,500/mo. The single 15% fund correctly captures the combined regular SS + WISP/MPF (mandatory provident fund) portions, which together total 15% up to the 35,000 MSC. employerFlatMonthly=30 models the employer-only Employees' Compensation (EC) contribution; NOTE this is approximated as PHP 30 (the amount for MSC \u2265 15,000) \u2014 it is actually only PHP 10 for MSC below 15,000, slightly overstating employer cost for low earners. PHILHEALTH (UHC Act RA 11223, Advisory PA2025-0002): premium held at 5% of monthly basic salary, split equally 2.5% employee / 2.5% employer, salary floor PHP 10,000, ceiling PHP 100,000 \u2014 employee and employer max PHP 2,500/mo each; rate and ceiling independently confirmed unchanged for 2026 (PIA). PAG-IBIG / HDMF (Circular 460, effective Feb 2024): Maximum Fund Salary doubled from PHP 5,000 to PHP 10,000; standard rate 2% employee / 2% employer capped at PHP 200 each per month. Approximation: members earning PHP 1,500/mo or below pay a reduced 1% employee rate (employer stays 2%); the standard 2%/2% is modelled here. All three funds (SSS, PhilHealth, Pag-IBIG) are mandatory for all covered private-sector employees regardless of nationality. No additional flat payroll levies exist in the Philippines (levies empty).",
  },
  // Malaysia — confidence: high. Tax year YA 2025 (resident progressive rates unchanged for YA 2024-2026); every band threshold and marginal rate independently confirmed against PwC Worldwide Tax Summaries and RinggitPlus (top 30% above RM2,000,000).
  MY: {
    code: "MY",
    name: "Malaysia",
    currency: "MYR",
    subunitDivisor: 100,
    taxYear: "2025 (YA 2025)",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 5000, rate: 0 },
        { min: 5000, max: 20000, rate: 1 },
        { min: 20000, max: 35000, rate: 3 },
        { min: 35000, max: 50000, rate: 6 },
        { min: 50000, max: 70000, rate: 11 },
        { min: 70000, max: 100000, rate: 19 },
        { min: 100000, max: 400000, rate: 25 },
        { min: 400000, max: 600000, rate: 26 },
        { min: 600000, max: 2000000, rate: 28 },
        { min: 2000000, max: Infinity, rate: 30 },
      ],
      annualAllowance: 9000,
      annualRebate: 0,
    },
    funds: [
      {
        name: "Employees Provident Fund (EPF / KWSP)",
        purpose: "pension",
        employeeRate: 11,
        employerRate: 12,
      },
      {
        name: "SOCSO / PERKESO (Employment Injury & Invalidity Scheme, First Category)",
        purpose: "disability",
        employeeRate: 0.5,
        employerRate: 1.75,
        monthlyCap: 6000,
      },
      {
        name: "Employment Insurance System (EIS / SIP)",
        purpose: "unemployment",
        employeeRate: 0.2,
        employerRate: 0.2,
        monthlyCap: 6000,
      },
    ],
    levies: [{ name: "HRD Corp Levy (HRDF)", rate: 1, paidBy: "employer", base: "gross" }],
    notes:
      "Tax year YA 2025 (resident progressive rates unchanged for YA 2024-2026); every band threshold and marginal rate independently confirmed against PwC Worldwide Tax Summaries and RinggitPlus (top 30% above RM2,000,000). Income-tax bands apply to CHARGEABLE income (gross minus reliefs). annualAllowance = RM9,000 models ONLY the universal individual/self relief; other reliefs (EPF relief up to RM4,000, life/medical/education insurance, RM2,500 lifestyle, spouse/child, etc.) are NOT modelled, so the config slightly OVERSTATES tax for employees claiming additional reliefs. The RM400 individual rebate (chargeable income <= RM35,000) is deliberately OMITTED (annualRebate unset): the kernel would subtract it universally and understate tax for the majority above that threshold, so instead low earners' tax is modestly overstated. The 0% band (RM0-5,000) is the first rate bracket on chargeable income and is distinct from the RM9,000 relief, so there is no double-counting. Non-residents are taxed at flat 30% (not modelled; resident rates assumed). EPF (KWSP, Third Schedule): employee 11%; employer 13% for monthly wages <= RM5,000 and 12% above RM5,000 - modelled at 12% per instruction (13% tier applies to lower-wage staff). EPF has no statutory wage ceiling but follows a rounded contribution table, so the flat % is a very close approximation. EPF is mandatory for Malaysian citizens/PRs; from 1 Oct 2025 (Finance Act 2025) non-citizen employees under 75 with valid passes and their employers must EACH contribute 2% (substitute 2%/2% for eligible foreign staff - not modelled). SOCSO/PERKESO First Category (Employment Injury + Invalidity, employees under 60): employer 1.75% + employee 0.5%, capped at the RM6,000/month wage ceiling in force since 1 Oct 2024 (fully mandatory from Apr 2025); officially table-based, giving near-exact figures at the cap (~RM104.15 employer / ~RM29.75 employee). Employees 60+ fall under a different Employment-Injury-only category (not modelled). EIS/SIP (Act 800): employee 0.2% + employer 0.2%, same RM6,000 ceiling (max ~RM11.90 each); table-based. HRDF levy: 1% of monthly wages (basic + fixed allowances), employer-only, base 'gross'; applies ONLY to employers registered with HRD Corp in covered sectors with 10+ Malaysian employees (0.5% optional for 5-9 employees) - include only for registered employers, otherwise treat as 0. All monthly caps are in MYR major units.",
  },
  // Thailand — confidence: high. Thailand statutory payroll config, verified mid-2026.
  TH: {
    code: "TH",
    name: "Thailand",
    currency: "THB",
    subunitDivisor: 100,
    taxYear: "2025/26",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 150000, rate: 0 },
        { min: 150000, max: 300000, rate: 5 },
        { min: 300000, max: 500000, rate: 10 },
        { min: 500000, max: 750000, rate: 15 },
        { min: 750000, max: 1000000, rate: 20 },
        { min: 1000000, max: 2000000, rate: 25 },
        { min: 2000000, max: 5000000, rate: 30 },
        { min: 5000000, max: Infinity, rate: 35 },
      ],
      annualAllowance: 160000,
      annualRebate: 0,
    },
    funds: [
      {
        name: "Social Security Fund (SSF)",
        purpose: "general",
        employeeRate: 5,
        employerRate: 5,
        monthlyCap: 17500,
        monthlyFloor: 1650,
      },
    ],
    notes:
      "Thailand statutory payroll config, verified mid-2026. Tax year is the calendar year (PwC labels the booklet 'Thai Tax 2025/26'). INCOME TAX: standard progressive PIT on NET assessable income, 0%-35%: 0-150k (0%, exempt), 150k-300k (5%), 300k-500k (10%), 500k-750k (15%), 750k-1M (20%), 1M-2M (25%), 2M-5M (30%), over 5M (35%). Confirmed against PwC Worldwide Tax Summaries (last reviewed Feb 2026) - rates and thresholds unchanged for 2025 and 2026. NOTE: the Thai Revenue Department's English page (rd.go.th/english/6045.html) still shows a stale pre-2017 schedule (35% over 4M, 30k personal allowance, 40%/60k expense deduction) and was NOT used; PwC and all current sources supersede it. ALLOWANCE: annualAllowance=160,000 THB models the two standard employment deductions that convert gross to net income for a single earner with no other reliefs - the 50%-of-income expense deduction capped at THB 100,000 (cap binds for anyone earning >=200k/yr), plus the THB 60,000 personal allowance. This is SEPARATE from and stacks with the 0%/150,000 first band (net-income exempt bracket), so the effective tax-free amount for a standard single employee is ~310,000 THB/yr. This is NOT double-counting: the deductions/allowances (applied to reach net income) and the exempt bracket (applied to net income) are distinct mechanisms in Thai law and the ~310k result matches the widely-cited figure. Additional statutory reliefs not modelled (spouse 60k, child 30k-60k each, parental care, life/health insurance, provident/RMF/SSF/ThaiESG contributions, mortgage interest up to 100k, and the deductible SSF contribution itself) would raise the tax-free amount further and are conservatively omitted. annualRebate=0 - Thailand has no flat PIT credit. Withholding is annualised monthly (PND 1); final liability via annual PND 90/91. FUNDS: Social Security Fund employee 5% / employer 5% of the monthly contribution base, base floored at THB 1,650 and capped at THB 17,500/month (max THB 875 each per month). The ceiling was THB 15,000 (max 750/mo) from 1995 to 31 Dec 2025; a Ministerial Regulation (Royal Gazette 12 Dec 2025) raised it to THB 17,500 effective 1 Jan 2026 (Phase 1, 2026-2028), rising to 20,000 in 2029-2031 and 23,000 from 2032; the 5% rate and 1,650 floor are unchanged. This config uses the currently-effective 2026 ceiling of 17,500 (verified independently via HLB Thailand and the SSO 2026 guidance, in addition to the BDO/Baker McKenzie sources). The SSF is a single combined fund (marked 'general') covering old-age pension, sickness/health, invalidity, maternity, death, child support and unemployment; not split by branch at employee level. ELIGIBILITY: SSF applies to employees under the Social Security Act, including foreign nationals holding valid work permits, subject to standard exemptions (civil servants, certain state-enterprise and seasonal workers). NOT modelled: the employer-only Workmen's Compensation Fund (WCF), an employer-paid premium of ~0.2%-1.0% of annual wages (capped base THB 240,000/yr) varying by industry risk class with no employee portion; and voluntary provident funds. COVID-era temporary SSF rate reductions have fully expired.",
  },
  // Vietnam — confidence: high. Vietnam statutory position for the 2026 calendar tax year as in force on 15 Jul 2026.
  VN: {
    code: "VN",
    name: "Vietnam",
    currency: "VND",
    subunitDivisor: 1,
    taxYear: "2026",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 120000000, rate: 5 },
        { min: 120000000, max: 360000000, rate: 10 },
        { min: 360000000, max: 720000000, rate: 20 },
        { min: 720000000, max: 1200000000, rate: 30 },
        { min: 1200000000, max: Infinity, rate: 35 },
      ],
      annualAllowance: 186000000,
      annualRebate: 0,
    },
    funds: [
      {
        name: "Social Insurance (BHXH)",
        purpose: "pension",
        employeeRate: 8,
        employerRate: 17.5,
        monthlyCap: 50600000,
      },
      {
        name: "Health Insurance (BHYT)",
        purpose: "health",
        employeeRate: 1.5,
        employerRate: 3,
        monthlyCap: 50600000,
      },
      {
        name: "Unemployment Insurance (BHTN)",
        purpose: "unemployment",
        employeeRate: 1,
        employerRate: 1,
        monthlyCap: 106200000,
      },
    ],
    notes:
      "Vietnam statutory position for the 2026 calendar tax year as in force on 15 Jul 2026. PIT: Law 109/2025/QH15 (passed 10 Dec 2025, effective 1 Jul 2026 and applied to the 2026 employment-income tax year) cut the resident schedule from 7 to 5 progressive brackets: 5/10/20/30/35% at monthly thresholds 10/30/60/100M VND (annual 120/360/720/1,200M). Verified that the ENACTED rates are 5/10/20/30/35 (bracket 2 cut 15->10%, bracket 3 cut 25->20% versus the draft), NOT the 5/15/25/30/35 draft; top rate 35% unchanged, now starting above 100M/month (was 80M). Resolution 110/2025/UBTVQH15 raised the personal/self deduction to 15.5M/month = 186M/yr (modeled as annualAllowance). Dependent deduction is 6.2M/month = 74.4M/yr each; it is person-specific and deliberately EXCLUDED from annualAllowance -- add 74.4M/yr per registered dependent for employees who claim them. KERNEL LIMITATION: Vietnamese PIT taxable income = gross - mandatory employee insurance (10.5%, capped) - personal/dependent deductions; the kernel only subtracts annualAllowance from gross and does NOT deduct the 10.5% SHUI, so it modestly overstates PIT (largest effect for salaries at/below the contribution caps). Progressive PIT applies to tax residents (>=183 days); non-residents pay a flat 20% on Vietnam-source employment income (not modeled). Social security (SHUI) rates unchanged: employee 8% SI + 1.5% HI + 1% UI = 10.5%; employer 17.5% SI (14% pension/death + 3% sickness/maternity + 0.5% occupational-accident, reducible to 0.3% for qualifying firms) + 3% HI + 1% UI = 21.5%. SI and HI base is capped at 20x the SI reference level (set equal to the public-sector base salary, which rose 2.34M->2.53M/month on 1 Jul 2026 per Decree 161/2026/ND-CP), giving the SI/HI cap of 50,600,000/month used here (the H1-2026 value was 46.8M). UI base is capped at 20x the regional minimum wage; under Decree 293/2025/ND-CP (effective 1 Jan 2026) Region I = 5,310,000/month, giving a Region I UI cap of 106,200,000 (Regions II/III/IV min wages 4,730,000/4,140,000/3,700,000 yield lower UI caps -- Region I used as representative/highest). A statutory SHUI base FLOOR equal to the regional minimum wage also applies but is omitted (moot at/above min wage). ELIGIBILITY: Unemployment insurance applies ONLY to Vietnamese nationals -- foreign employees are exempt from UI (set UI to 0 for foreigners) but foreign employees on Vietnamese labor contracts of 12+ months ARE subject to compulsory SI and HI at the same 8%/1.5% employee and 17.5%/3% employer rates. Not modeled: employers also pay a 2% trade-union contribution on the (capped) SI salary fund. VND has no minor unit (hao/xu obsolete), so subunitDivisor=1. Confidence high: PIT brackets/rates, all SHUI rates, and the 2026 SI/HI cap (50.6M) and UI Region I cap (106.2M) each confirmed against multiple independent 2026 sources (EY, KPMG, Roedl, Acclime, PwC, Vietnam Briefing, NetViet, Alitium).",
  },
  // Nigeria — confidence: high. Tax year: Nigeria Tax Act (NTA) 2025 PAYE regime EFFECTIVE 1 JANUARY 2026 (calendar tax year).
  NG: {
    code: "NG",
    name: "Nigeria",
    currency: "NGN",
    subunitDivisor: 100,
    taxYear: "2026 (Nigeria Tax Act 2025, effective 1 Jan 2026)",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 800000, rate: 0 },
        { min: 800000, max: 3000000, rate: 15 },
        { min: 3000000, max: 12000000, rate: 18 },
        { min: 12000000, max: 25000000, rate: 21 },
        { min: 25000000, max: 50000000, rate: 23 },
        { min: 50000000, max: Infinity, rate: 25 },
      ],
      annualAllowance: 500000,
      annualRebate: 0,
    },
    funds: [
      {
        name: "Contributory Pension Scheme (CPS)",
        purpose: "pension",
        employeeRate: 8,
        employerRate: 10,
      },
      {
        name: "National Housing Fund (NHF)",
        purpose: "housing",
        employeeRate: 2.5,
        employerRate: 0,
      },
      {
        name: "NSITF Employees' Compensation Scheme (ECS)",
        purpose: "disability",
        employeeRate: 0,
        employerRate: 1,
      },
      {
        name: "Industrial Training Fund (ITF)",
        purpose: "training",
        employeeRate: 0,
        employerRate: 1,
      },
    ],
    notes:
      "Tax year: Nigeria Tax Act (NTA) 2025 PAYE regime EFFECTIVE 1 JANUARY 2026 (calendar tax year). Independently reconfirmed against KPMG flash-alert 2025-168 and Adeola Oyinlade & Co: the six-band schedule (0/15/18/21/23/25%) with thresholds 800k / 3m / 12m / 25m / 50m is correct and supersedes the repealed old PITA bands (7/11/15/19/21/24%) and the repealed Consolidated Relief Allowance (CRA = higher of NGN200k or 1% of gross, plus 20% of gross). For income earned Jan-Dec 2025 the OLD PITA/CRA rules still apply. TAX-FREE / ALLOWANCE MODELLING: the NGN800,000 exemption is modelled as the first 0% band. The CRA is replaced by 'rent relief' = the LOWER of 20% of annual rent actually paid OR NGN500,000 (confirmed). Rent relief is a genuinely SEPARATE pre-schedule deduction from the 0% band, so setting annualAllowance=500,000 alongside the 800k 0% band does NOT double-count. It is CONDITIONAL (only renters who declare rent with documentation qualify), so this is an APPROXIMATION representing a typical urban renter who maxes the cap; set annualAllowance to 0 for homeowners / non-claimants to avoid under-withholding. KERNEL LIMITATION: pension (8%) and NHF (2.5%) contributions (plus life-insurance premiums, mortgage interest, NHIA) are ALSO statutorily deductible from chargeable income under the NTA 2025, but as percentage-of-pay reliefs they cannot be represented as a flat annualAllowance in this fixed kernel; for contributing formal-sector employees these unmodelled reliefs exceed the 500k rent cap, so the computed PAYE is a modest OVER-estimate that offsets the rent-relief default. No separate minimum-wage line: the NGN800,000 0% band exceeds the annual national minimum wage (NGN70,000/month = NGN840,000/yr), so minimum-wage earners fall in/near the exempt band. FUNDS (all rates reconfirmed via SIAO, MyWorkPay, PenCom): Pension CPS (Pension Reform Act 2014) employee 8% / employer 10% of monthly emolument (statutorily basic + housing + transport, NOT full gross) \u2014 mandatory for employers with 15+ employees, uncapped; the engine applies the rate to grossMonthly, which may slightly overstate the base where gross exceeds basic+housing+transport. NHF employee 2.5% of monthly BASIC salary (engine uses gross as a proxy, may overstate); post-reform NHF is MANDATORY for public-sector but VOLUNTARY for private-sector employees, so set to 0 for private employers who do not opt in. NSITF Employees' Compensation Scheme (Employees' Compensation Act 2010) is EMPLOYER-ONLY 1% of total monthly payroll (mapped to 'disability' as it funds work-injury/disability compensation); applies to any employer with 1+ employee. ITF (Industrial Training Fund Act) is EMPLOYER-ONLY 1% of payroll but only for employers with 5+ employees OR annual turnover >= NGN50m, and is remitted ANNUALLY (by 1 April); expressed here as a 1% employer rate because 1% monthly x12 = 1% annual for cost-modelling \u2014 omit for smaller employers, and note up to 50% may be refundable for compliant training. LEVIES: none apply to payroll (the NTA 2025 'Development Levy' of ~4% is on company assessable profits, not a payroll deduction), so levies=[]. HEALTH (NHIA Act 2022): a statutory formal-sector rate DOES exist \u2014 the public-sector social health insurance programme is ~15% of basic salary (employer 10% / employee 5%) OR ~5% of consolidated payroll (employer 3.5% / employee 1.5%), mandatory for employers with 5+ staff \u2014 but it is EXCLUDED from funds here because there is no single universally-applied private-sector payroll percentage (many private employers satisfy the mandate via HMO/private plans at negotiated rates, and the employer may elect to bear 100%), so including a fixed rate would over-deduct for most private employees; add an employee 5% / employer 10% of basic health fund when modelling a public-sector or basic-salary-method employer. All monetary values are in naira (major unit); subunitDivisor 100 (kobo). Confidence high: every load-bearing figure (all six PIT bands incl. 25% top rate and thresholds, rent-relief 500k cap, pension 8/10, NHF 2.5, NSITF 1, ITF 1) confirmed against current 2025/2026 authoritative sources.",
  },
  // Kenya — confidence: high. Tax year 2025/26 (Kenya PAYE is a monthly regime; the individual year of income is the calendar year, labelled 2025/26 here).
  KE: {
    code: "KE",
    name: "Kenya",
    currency: "KES",
    subunitDivisor: 100,
    taxYear: "2025/26",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 288000, rate: 10 },
        { min: 288000, max: 388000, rate: 25 },
        { min: 388000, max: 6000000, rate: 30 },
        { min: 6000000, max: 9600000, rate: 32.5 },
        { min: 9600000, max: Infinity, rate: 35 },
      ],
      annualAllowance: 0,
      annualRebate: 28800,
    },
    funds: [
      {
        name: "NSSF (National Social Security Fund)",
        purpose: "pension",
        employeeRate: 6,
        employerRate: 6,
        monthlyCap: 108000,
      },
      {
        name: "SHIF / SHA (Social Health Insurance Fund)",
        purpose: "health",
        employeeRate: 2.75,
        employerRate: 0,
        monthlyFloor: 10909.09,
      },
      {
        name: "Affordable Housing Levy (AHL)",
        purpose: "housing",
        employeeRate: 1.5,
        employerRate: 1.5,
      },
      {
        name: "NITA Industrial Training Levy",
        purpose: "training",
        employeeRate: 0,
        employerRate: 0,
        employerFlatMonthly: 50,
      },
    ],
    notes:
      "Tax year 2025/26 (Kenya PAYE is a monthly regime; the individual year of income is the calendar year, labelled 2025/26 here). All load-bearing numbers independently re-verified July 2026. INCOME TAX: progressive annual bands 10% <=288,000; 25% 288,000-388,000; 30% 388,000-6,000,000; 32.5% 6,000,000-9,600,000; 35% >9,600,000 (top band max set to 1,000,000,000,000 = engine sentinel for infinity). Unchanged since 1 July 2023 (Finance Act 2023), confirmed still in force for 2025/26 by PwC (page reviewed Dec 2025) and KRA. Monthly equivalents: 24,000 / 32,333 / 500,000 / 800,000. Kenya has NO tax-free threshold, so annualAllowance=0; the resident personal relief of KES 2,400/month = KES 28,800/year is a flat tax CREDIT modelled as annualRebate (subtracted AFTER the bands, not from taxable pay). NSSF: Phase 4 of the NSSF Act 2013 is IN FORCE (effective 1 Feb 2026), 6% employee + 6% employer on pensionable pay up to Upper Earnings Limit KES 108,000, i.e. employee contribution = 6% of min(gross,108,000), max KES 6,480 each side; Tier I + Tier II combine to a single 6% of capped pay so no floor is needed. Modelled as a pension fund with monthlyCap 108,000. Prior UEL of KES 72,000 (max 4,320) was Phase 3 (Feb 2025-Jan 2026); since today is July 2026 the config correctly uses 108,000 (PwC's other-taxes page still lags at 4,320 but KPMG's Feb-2026 tax alert and multiple 2026 sources confirm Phase 4 is live). If you specifically need the Feb-2025-to-Jan-2026 basis, set monthlyCap to 72,000. SHIF/SHA replaced NHIF Oct 2024: 2.75% of gross, EMPLOYEE-ONLY (no employer share), minimum KES 300/month and NO ceiling; the 300 floor is modelled via monthlyFloor=10,909.09 (=300/0.0275) so anyone earning below that pays exactly 300 (confirmed EY + KRA/SHA). Affordable Housing Levy: 1.5% employee + 1.5% employer of gross, uncapped, modelled as a housing fund with both sides in one entry (confirmed PwC). NITA industrial-training levy KES 50 per employee per month is EMPLOYER-ONLY (flat, no employee deduction, does not affect net pay); applies to employers registered/liable with NITA (collection shifting to KRA) - included for employer-cost completeness only. KEY ENGINE LIMITATION: under the Tax Laws (Amendment) Act 2024 (effective 27 Dec 2024) employee NSSF, SHIF and AHL contributions are ALLOWABLE DEDUCTIONS from taxable pay BEFORE PAYE. The fixed kernel applies the bands to gross*12 (minus annualAllowance) and cannot subtract these income-dependent, capped contributions, so the PAYE it produces is modestly OVERSTATED versus statutory reality (the un-modelled deduction is roughly 6% of capped NSSF pay + 2.75% SHIF + 1.5% AHL of gross). If the engine later supports pre-tax statutory deductions, feed it gross minus (NSSF + SHIF + AHL) before the bands. All monetary values are monthly KES major units; subunitDivisor=100. Every load-bearing number (top rate 35%, all band thresholds, personal relief 28,800, NSSF 6%/6% + UEL 108,000, SHIF 2.75% + 300 floor, AHL 1.5%+1.5%, NITA 50) was confirmed against current 2025/2026 sources.",
  },
  // Egypt — confidence: high. Tax year 2025/2026 (Egypt runs a calendar tax year; income-tax bands are identical for 2025 and 2026 per PwC and Andersen).
  EG: {
    code: "EG",
    name: "Egypt",
    currency: "EGP",
    subunitDivisor: 100,
    taxYear: "2025/2026",
    incomeTax: {
      system: "progressive",
      annualBands: [
        { min: 0, max: 40000, rate: 0 },
        { min: 40000, max: 55000, rate: 10 },
        { min: 55000, max: 70000, rate: 15 },
        { min: 70000, max: 200000, rate: 20 },
        { min: 200000, max: 400000, rate: 22.5 },
        { min: 400000, max: 1200000, rate: 25 },
        { min: 1200000, max: Infinity, rate: 27.5 },
      ],
      annualAllowance: 20000,
      annualRebate: 0,
    },
    funds: [
      {
        name: "Social Insurance (NOSI comprehensive scheme, Law 148/2019)",
        purpose: "pension",
        employeeRate: 11,
        employerRate: 18.75,
        monthlyCap: 16700,
        monthlyFloor: 2700,
      },
    ],
    notes:
      "Tax year 2025/2026 (Egypt runs a calendar tax year; income-tax bands are identical for 2025 and 2026 per PwC and Andersen). INCOME TAX (all thresholds annual EGP, independently confirmed against PwC Worldwide Tax Summaries + Andersen + RemotePeople): 0% up to 40,000; 10% 40k-55k; 15% 55k-70k; 20% 70k-200k; 22.5% 200k-400k; 25% 400k-1.2M; 27.5% above 1.2M. annualAllowance=20,000 is the statutory annual salary-tax exemption granted to BOTH residents and non-residents; PwC states it is a separate allowance 'distinct from the zero-percent first bracket', so it STACKS with the 0% 0-40,000 band (Andersen confirms it is deducted first, then the brackets apply to the remainder). Modelling both the 20,000 allowance and the 0% band is therefore correct, not double-counting: a low earner is effectively tax-free to ~60,000 EGP/yr. APPROXIMATIONS: (1) Egypt applies a bracket-tapering rule that progressively removes lower brackets as net annual taxable income rises (0%+10% removed above 600,000; +15% above 700,000; +20% above 800,000; +22.5% above 900,000; and 27.5% applies from the first pound once net income exceeds 1,200,000). The config encodes the STANDARD table applicable to net taxable income up to 600,000 EGP, covering the large majority of salaried employees; for high earners (>600k net/yr) this config understates tax. (2) Employee social-insurance contributions are legally deductible from the income-tax base, but the fixed kernel only subtracts annualAllowance, so income tax is modestly OVERSTATED for employees within the SI cap (deduction foregone up to ~11% of the capped base). SOCIAL INSURANCE: Single comprehensive NOSI scheme under Law 148/2019 covering old-age/disability/death pension, work-injury, sickness and unemployment; employee 11% / employer 18.75% of the insurable wage (total 29.75%), confirmed by PwC and multiple sources, modeled as one fund with purpose=pension as the dominant component. Insurable-wage floor/cap are the values EFFECTIVE 1 JANUARY 2026 and currently in force: EGP 2,700 monthly floor / EGP 16,700 monthly cap (2025 values were 2,300 / 14,500), confirmed by PwC, BDO and Mercans. These limits rise ~15% each 1 January through the phase-in period (started 2021), so re-verify each January. ELIGIBILITY/EDGE CASES: Company managers and board members entered in the commercial register instead pay a flat 21% on the maximum insurable wage - not modeled. Config assumes a standard resident or non-resident salaried employee (both receive the 20,000 exemption). No separate statutory payroll levies apply. subunitDivisor=100 (piastres).",
  },
};
